import {CodexExecutionError,type CodexExecutor, type ExecutionResult} from "./codex-executor.js";
import {fallbackEnvironment,isFallbackIsolationError,openRouterConfig,type FallbackIsolation} from "./core.js";
import {fetchCatalog,isExactFreeId,preflightExactModel,qualifyModel,type FetchLike} from "@print-engineer/openrouter-free-selector";
export const COMPATIBILITY_PROMPT="Using repository tools, read AGENTS.md from the current worktree. Do not edit anything. Report the first Markdown heading and finish.";
export const COMPATIBILITY_PROBE_FAILED="COMPATIBILITY_PROBE_FAILED";
export const COMPATIBILITY_PROBE_RATE_LIMITED="COMPATIBILITY_PROBE_RATE_LIMITED";
export class CompatibilityProbeError extends Error {constructor(public readonly code:typeof COMPATIBILITY_PROBE_FAILED|typeof COMPATIBILITY_PROBE_RATE_LIMITED){super(code);}}
export function isCompatibilityProbeRateLimited(error:unknown):error is CompatibilityProbeError{return error instanceof CompatibilityProbeError&&error.code===COMPATIBILITY_PROBE_RATE_LIMITED;}
export function compatibilityModel(value:string|undefined){const model=value?.trim();if(!model||model.includes(",")||/\s/.test(model)||!isExactFreeId(model))throw new Error("COMPATIBILITY_PROBE_FAILED");return model;}
function isRecord(value:unknown):value is Record<string,unknown>{return typeof value==="object"&&value!==null&&!Array.isArray(value);}
function hasStructuredHttp429(value:unknown):boolean{if(!isRecord(value))return false;const info=value.codex_error_info;if(!isRecord(info))return false;const rateLimit=info.response_too_many_failed_attempts;return isRecord(rateLimit)&&rateLimit.http_status_code===429;}
function eventHasStructuredHttp429(event:unknown):boolean{if(!isRecord(event))return false;return hasStructuredHttp429(event)||hasStructuredHttp429(event.error)||hasStructuredHttp429(event.item);}
export function evaluateProbe(result:ExecutionResult,before:string,after:string){const rateLimited=result.events.some(eventHasStructuredHttp429);const failed=result.events.some(e=>e.type==="turn.failed"||e.type==="error"||("item" in e&&e.item.type==="error"));if(rateLimited&&failed&&after===before)throw new CompatibilityProbeError(COMPATIBILITY_PROBE_RATE_LIMITED);const started=result.events.some(e=>e.type==="thread.started");const command=result.events.some(e=>e.type==="item.completed"&&e.item.type==="command_execution"&&e.item.status==="completed"&&e.item.exit_code===0&&/(^|[\\/\s'\"])(AGENTS\.md)(?:$|[\s'\"])/.test(e.item.command));const completed=result.events.some(e=>e.type==="turn.completed")&&result.finalResponse.trim()!=="";if(failed||!started||!command||!completed||after!==before)throw new CompatibilityProbeError(COMPATIBILITY_PROBE_FAILED);}
export async function runCompatibilityProbe(executor:CodexExecutor,model:string,workingDirectory:string,env:NodeJS.ProcessEnv,before:string,after:()=>string,_now=new Date(),isolation:FallbackIsolation={}){let result:ExecutionResult;try{result=await executor.execute({config:openRouterConfig(),env:fallbackEnvironment(env,isolation)},{model,workingDirectory,sandboxMode:"read-only",approvalPolicy:"never",networkAccessEnabled:false,webSearchMode:"disabled"},COMPATIBILITY_PROMPT);}catch(error){if(isFallbackIsolationError(error))throw error;if(error instanceof CodexExecutionError&&error.httpStatus===429)throw new CompatibilityProbeError(COMPATIBILITY_PROBE_RATE_LIMITED);throw new Error("COMPATIBILITY_PROBE_FAILED");}evaluateProbe(result,before,after());return{model_id:model,codex_sdk_version:"0.147.0",provider_id:"openrouter",wire_api:"responses",tool_loop_success:true,final_completion_success:true,worktree_unchanged:true};}
export interface ProbeDependencies{fetcher:FetchLike;executor:CodexExecutor;gitStatus(workdir:string):string;now():Date;isolation?:FallbackIsolation}
export async function executeCompatibilityProbe(env:NodeJS.ProcessEnv,workdir:string,deps:ProbeDependencies){try{if(env.CODEX_PROVIDER_MODE?.trim().toLowerCase()!=="openrouter-free")throw 0;const key=env.OPENROUTER_API_KEY;if(!key?.trim())throw 0;const model=compatibilityModel(env.CODEX_COMPATIBILITY_MODEL);const catalog=await fetchCatalog(deps.fetcher,key,"build");const record=catalog.find(x=>x.id===model);if(!record||!qualifyModel(record,deps.now()))throw 0;await preflightExactModel(deps.fetcher,key,model,deps.now());const before=deps.gitStatus(workdir);return await runCompatibilityProbe(deps.executor,model,workdir,env,before,()=>deps.gitStatus(workdir),deps.now(),deps.isolation);}catch(error){if(isFallbackIsolationError(error)||isCompatibilityProbeRateLimited(error))throw error;throw new CompatibilityProbeError(COMPATIBILITY_PROBE_FAILED);}}
export function safeProbeLines(report:Awaited<ReturnType<typeof runCompatibilityProbe>>){return Object.entries(report).map(([k,v])=>`${k}=${String(v)}`);}
