import {CodexExecutionError,type CodexExecutor, type ExecutionResult} from "./codex-executor.js";
import {fallbackEnvironment,isFallbackIsolationError,openRouterConfig,type FallbackIsolation} from "./core.js";
import {fetchCatalog,isExactFreeId,preflightExactModel,qualifyModel,type FetchLike} from "@print-engineer/openrouter-free-selector";
import {lstatSync,readdirSync,readFileSync} from "node:fs";
import {isAbsolute,join,relative,resolve} from "node:path";
export const COMPATIBILITY_PROMPT="Using repository tools, read AGENTS.md from the current worktree. Do not edit anything. Report the first Markdown heading and finish.";
export const COMPATIBILITY_PROBE_FAILED="COMPATIBILITY_PROBE_FAILED";
export const COMPATIBILITY_PROBE_RATE_LIMITED="COMPATIBILITY_PROBE_RATE_LIMITED";
export class CompatibilityProbeError extends Error {constructor(public readonly code:typeof COMPATIBILITY_PROBE_FAILED|typeof COMPATIBILITY_PROBE_RATE_LIMITED){super(code);}}
export function isCompatibilityProbeRateLimited(error:unknown):error is CompatibilityProbeError{return error instanceof CompatibilityProbeError&&error.code===COMPATIBILITY_PROBE_RATE_LIMITED;}
export function compatibilityModel(value:string|undefined){const model=value?.trim();if(!model||model.includes(",")||/\s/.test(model)||!isExactFreeId(model))throw new Error("COMPATIBILITY_PROBE_FAILED");return model;}
function isRecord(value:unknown):value is Record<string,unknown>{return typeof value==="object"&&value!==null&&!Array.isArray(value);}
function hasStructuredHttp429(value:unknown):boolean{if(!isRecord(value))return false;const info=value.codex_error_info;if(!isRecord(info))return false;const rateLimit=info.response_too_many_failed_attempts;return isRecord(rateLimit)&&rateLimit.http_status_code===429;}
function eventHasStructuredHttp429(event:unknown):boolean{if(!isRecord(event))return false;return hasStructuredHttp429(event)||hasStructuredHttp429(event.error)||hasStructuredHttp429(event.item);}
interface RolloutTerminal{status:number}
interface RolloutMetadata{kind:"session"|"turn_context"|"terminal";threadId:string;provider:string;cwd:string;model?:string;modelPresent:boolean;terminal?:RolloutTerminal}
function metadataField(payload:Record<string,unknown>|undefined,value:Record<string,unknown>,...keys:string[]):{present:boolean;value?:string}{const values:unknown[]=[];for(const source of [payload,value])if(source)for(const key of keys)if(Object.prototype.hasOwnProperty.call(source,key))values.push(source[key]);if(values.some(item=>typeof item!=="string"))throw new Error("ROLLOUT_UNCORRELATED");const distinct=[...new Set(values)];if(distinct.length>1)throw new Error("ROLLOUT_UNCORRELATED");return{present:values.length>0,value:typeof distinct[0]==="string"?distinct[0]:undefined};}
export function isPathContained(root:string,candidate:string):boolean{const normalizedRoot=resolve(root);const normalizedCandidate=resolve(candidate);const child=relative(normalizedRoot,normalizedCandidate);return child===""||(!child.startsWith("..")&&!isAbsolute(child));}
type RolloutReader={readdir(path:string):string[];readFile(path:string):string;lstat(path:string):{isDirectory():boolean;isSymbolicLink():boolean;isReparsePoint?():boolean}};
function linked(metadata:ReturnType<RolloutReader["lstat"]>):boolean{return metadata.isSymbolicLink()||metadata.isReparsePoint?.()===true;}
function rolloutFiles(home:string,reader:RolloutReader):string[]{const files:string[]=[];const visit=(path:string)=>{if(!isPathContained(home,path))throw new Error("ROLLOUT_UNREADABLE");let rootMetadata;try{rootMetadata=reader.lstat(path);}catch{throw new Error("ROLLOUT_UNREADABLE");}if(linked(rootMetadata)||!rootMetadata.isDirectory())throw new Error("ROLLOUT_UNREADABLE");let entries:string[];try{entries=reader.readdir(path);}catch{throw new Error("ROLLOUT_UNREADABLE");}for(const entry of entries){const child=join(path,entry);if(!isPathContained(home,child))throw new Error("ROLLOUT_UNREADABLE");let metadata;try{metadata=reader.lstat(child);}catch{throw new Error("ROLLOUT_UNREADABLE");}if(linked(metadata))throw new Error("ROLLOUT_UNREADABLE");if(metadata.isDirectory())visit(child);else if(entry.startsWith("rollout-")&&entry.endsWith(".jsonl"))files.push(child);}};visit(home);return files;}
function rolloutRecord(value:unknown):RolloutMetadata|undefined{if(!isRecord(value))return undefined;const payload=isRecord(value.payload)?value.payload:undefined;let terminal:RolloutTerminal|undefined;if(payload?.type==="task_complete"&&isRecord(payload.error)){const errorInfo=payload.error.codex_error_info;if(isRecord(errorInfo)&&isRecord(errorInfo.response_too_many_failed_attempts)&&typeof errorInfo.response_too_many_failed_attempts.http_status_code==="number")terminal={status:errorInfo.response_too_many_failed_attempts.http_status_code};}if(terminal)return{kind:"terminal",threadId:"",provider:"",cwd:"",modelPresent:false,terminal};if(value.type==="turn_context"){const model=metadataField(payload,value,"model","model_id");return model.present?{kind:"turn_context",threadId:"",provider:"",cwd:"",model:model.value,modelPresent:true}:undefined;}if(value.type!=="session_meta")return undefined;const threadId=metadataField(payload,value,"id","thread_id","threadId","session_id");const provider=metadataField(payload,value,"model_provider","provider","provider_id");const cwd=metadataField(payload,value,"cwd","working_directory","workdir");const model=metadataField(payload,value,"model","model_id");return{kind:"session",threadId:threadId.value??"",provider:provider.value??"",cwd:cwd.value??"",model:model.value,modelPresent:model.present};}
function correlatedRollout429(home:string,threadId:string,workingDirectory:string,intendedModel:string|undefined,isolation:FallbackIsolation):number|undefined{const injected=isolation.filesystem?.readdir&&isolation.filesystem.readFile?{readdir:isolation.filesystem.readdir.bind(isolation.filesystem),readFile:isolation.filesystem.readFile.bind(isolation.filesystem),lstat:isolation.filesystem.lstat.bind(isolation.filesystem)}:undefined;const reader:RolloutReader=injected??{readdir:(path:string)=>readdirSync(path),readFile:(path:string)=>readFileSync(path,"utf8"),lstat:(path:string)=>lstatSync(path)};let matched=0;let status:number|undefined;for(const file of rolloutFiles(home,reader)){const sessions:RolloutMetadata[]=[];const models:string[]=[];let terminalStatus:number|undefined;let lines:string[];try{lines=reader.readFile(file).split(/\r?\n/).filter(Boolean);}catch{throw new Error("ROLLOUT_UNREADABLE");}for(const line of lines){let parsed:unknown;try{parsed=JSON.parse(line);}catch{throw new Error("ROLLOUT_CORRUPT");}const record=rolloutRecord(parsed);if(!record)continue;if(record.kind==="session")sessions.push(record);if(record.modelPresent){if(record.model===undefined)throw new Error("ROLLOUT_UNCORRELATED");models.push(record.model);}if(record.terminal)terminalStatus=record.terminal.status;}if(sessions.length===0)continue;if(sessions.some(record=>!record.threadId||!record.provider||!record.cwd))throw new Error("ROLLOUT_UNCORRELATED");const first=sessions[0];if(sessions.some(record=>record.threadId!==first.threadId||record.provider!==first.provider||record.cwd!==first.cwd))throw new Error("ROLLOUT_UNCORRELATED");if(first.threadId!==threadId)continue;if(first.provider!=="openrouter"||first.cwd!==workingDirectory)throw new Error("ROLLOUT_UNCORRELATED");if(intendedModel===undefined||models.length===0||models.some(model=>model!==intendedModel)||new Set(models).size!==1)throw new Error("ROLLOUT_UNCORRELATED");matched++;if(terminalStatus!==undefined)status=terminalStatus;}if(matched!==1)throw new Error("ROLLOUT_UNCORRELATED");return status;}
export function evaluateProbe(result:ExecutionResult,before:string,after:string){const rateLimited=result.events.some(eventHasStructuredHttp429);const failed=result.events.some(e=>e.type==="turn.failed"||e.type==="error"||("item" in e&&e.item.type==="error"));if(rateLimited&&failed&&after===before)throw new CompatibilityProbeError(COMPATIBILITY_PROBE_RATE_LIMITED);const started=result.events.some(e=>e.type==="thread.started");const command=result.events.some(e=>e.type==="item.completed"&&e.item.type==="command_execution"&&e.item.status==="completed"&&e.item.exit_code===0&&/(^|[\\/\s'\"])(AGENTS\.md)(?:$|[\s'\"])/.test(e.item.command));const completed=result.events.some(e=>e.type==="turn.completed")&&result.finalResponse.trim()!=="";if(failed||!started||!command||!completed||after!==before)throw new CompatibilityProbeError(COMPATIBILITY_PROBE_FAILED);}
export async function runCompatibilityProbe(executor:CodexExecutor,model:string,workingDirectory:string,env:NodeJS.ProcessEnv,before:string,after:()=>string,_now=new Date(),isolation:FallbackIsolation={}){let result:ExecutionResult;let preparedHome:string|undefined;try{const fallback=fallbackEnvironment(env,isolation);preparedHome=fallback.CODEX_HOME;result=await executor.execute({config:openRouterConfig(),env:fallback},{model,workingDirectory,sandboxMode:"read-only",approvalPolicy:"never",networkAccessEnabled:false,webSearchMode:"disabled"},COMPATIBILITY_PROMPT);}catch(error){if(isFallbackIsolationError(error))throw error;const unchanged=after()===before;if(!unchanged)throw new CompatibilityProbeError(COMPATIBILITY_PROBE_FAILED);if(error instanceof CodexExecutionError&&error.httpStatus===429)throw new CompatibilityProbeError(COMPATIBILITY_PROBE_RATE_LIMITED);if(error instanceof CodexExecutionError&&error.threadId&&preparedHome){try{if(correlatedRollout429(preparedHome,error.threadId,workingDirectory,model,isolation)===429)throw new CompatibilityProbeError(COMPATIBILITY_PROBE_RATE_LIMITED);}catch(rolloutError){if(rolloutError instanceof CompatibilityProbeError)throw rolloutError;}}throw new Error("COMPATIBILITY_PROBE_FAILED");}evaluateProbe(result,before,after());return{model_id:model,codex_sdk_version:"0.147.0",provider_id:"openrouter",wire_api:"responses",tool_loop_success:true,final_completion_success:true,worktree_unchanged:true};}
export interface ProbeDependencies{fetcher:FetchLike;executor:CodexExecutor;gitStatus(workdir:string):string;now():Date;isolation?:FallbackIsolation}
export async function executeCompatibilityProbe(env:NodeJS.ProcessEnv,workdir:string,deps:ProbeDependencies){try{if(env.CODEX_PROVIDER_MODE?.trim().toLowerCase()!=="openrouter-free")throw 0;const key=env.OPENROUTER_API_KEY;if(!key?.trim())throw 0;const model=compatibilityModel(env.CODEX_COMPATIBILITY_MODEL);const catalog=await fetchCatalog(deps.fetcher,key,"build");const record=catalog.find(x=>x.id===model);if(!record||!qualifyModel(record,deps.now()))throw 0;await preflightExactModel(deps.fetcher,key,model,deps.now());const before=deps.gitStatus(workdir);return await runCompatibilityProbe(deps.executor,model,workdir,env,before,()=>deps.gitStatus(workdir),deps.now(),deps.isolation);}catch(error){if(isFallbackIsolationError(error)||isCompatibilityProbeRateLimited(error))throw error;throw new CompatibilityProbeError(COMPATIBILITY_PROBE_FAILED);}}
export function safeProbeLines(report:Awaited<ReturnType<typeof runCompatibilityProbe>>){return Object.entries(report).map(([k,v])=>`${k}=${String(v)}`);}
