import {existsSync,lstatSync,mkdirSync} from "node:fs";
import {isAbsolute,resolve} from "node:path";
import type {BuildProducer,FetchLike,PlanProducer} from "@print-engineer/openrouter-free-selector";
export type CodexPhase="general"|"plan"|"build"|"review";export type ProviderMode="auto"|"primary"|"openrouter-free";export type ReviewTarget="plan"|"implementation";
export const PREFERRED_MODEL="gpt-5.6-sol";
export function parseProviderMode(v:string|undefined):ProviderMode{const n=v?.trim().toLowerCase()||"auto";if(n!=="auto"&&n!=="primary"&&n!=="openrouter-free")throw new Error("INVALID_PROVIDER_MODE");return n;}
export function parsePhase(v:string|undefined):CodexPhase{const n=v?.trim().toLowerCase()||"general";if(!["general","plan","build","review"].includes(n))throw new Error("CODEX_PHASE must be one of: general, plan, build, review.");return n as CodexPhase;}
export function parseReviewTarget(v:string|undefined):ReviewTarget|undefined{if(v===undefined||!v.trim())return undefined;const n=v.trim().toLowerCase();if(n!=="plan"&&n!=="implementation")throw new Error("INVALID_REVIEW_TARGET");return n;}
const FALLBACK_ALLOW=["PATH","PATHEXT","SYSTEMROOT","WINDIR","COMSPEC","TEMP","TMP","USERPROFILE","APPDATA","LOCALAPPDATA","PROGRAMDATA","PROGRAMFILES","PROGRAMFILES(X86)","PROCESSOR_ARCHITECTURE","NUMBER_OF_PROCESSORS","TERM","COLORTERM","NO_COLOR","OPENROUTER_API_KEY"];
export function primaryEnvironment(env:NodeJS.ProcessEnv):Record<string,string>{const out:Record<string,string>={};for(const [key,value] of Object.entries(env))if(value!==undefined&&key.toLowerCase()!=="openrouter_api_key"&&FALLBACK_ALLOW.some(x=>x.toLowerCase()===key.toLowerCase()))out[key]=value;return out;}
export interface FallbackFilesystem {mkdir(path:string,options:{recursive:true}):void;lstat(path:string):{isDirectory():boolean;isSymbolicLink():boolean};exists(path:string):boolean;readdir?(path:string):string[];readFile?(path:string):string;}
const defaultFallbackFilesystem:FallbackFilesystem={mkdir:(path,options)=>mkdirSync(path,options),lstat:path=>lstatSync(path),exists:path=>existsSync(path)};
export interface FallbackIsolation {filesystem?:FallbackFilesystem;localAppData?:string;}
export interface PreparedFallback {environment:Record<string,string>;home:string;}
export const OPENROUTER_CODEX_HOME_INVALID="OPENROUTER_CODEX_HOME_INVALID";
export const OPENROUTER_CODEX_HOME_AUTH_PRESENT="OPENROUTER_CODEX_HOME_AUTH_PRESENT";
export function isFallbackIsolationError(error:unknown):error is Error{return error instanceof Error&&(error.message===OPENROUTER_CODEX_HOME_INVALID||error.message===OPENROUTER_CODEX_HOME_AUTH_PRESENT);}
export function fallbackHomePath(localAppData:string):string {if(!localAppData.trim()||!isAbsolute(localAppData))throw new Error("OPENROUTER_CODEX_HOME_INVALID");return resolve(localAppData,"print-engineer-codex","openrouter-home-v1");}
function validateFallbackDirectory(path:string,filesystem:FallbackFilesystem):void {try{const metadata=filesystem.lstat(path);if(!metadata.isDirectory()||metadata.isSymbolicLink())throw new Error("invalid");}catch{throw new Error("OPENROUTER_CODEX_HOME_INVALID");}}
export function prepareFallbackExecution(env:NodeJS.ProcessEnv,isolation:FallbackIsolation={}):PreparedFallback {
  const filesystem=isolation.filesystem??defaultFallbackFilesystem;
  const localAppData=Object.prototype.hasOwnProperty.call(env,"LOCALAPPDATA")?env.LOCALAPPDATA:(isolation.localAppData??env.LOCALAPPDATA);
  if(!localAppData?.trim()||!isAbsolute(localAppData))throw new Error("OPENROUTER_CODEX_HOME_INVALID");
  const parent=resolve(localAppData,"print-engineer-codex"),home=resolve(parent,"openrouter-home-v1");
  try{filesystem.mkdir(parent,{recursive:true});filesystem.mkdir(home,{recursive:true});}catch{throw new Error("OPENROUTER_CODEX_HOME_INVALID");}
  validateFallbackDirectory(parent,filesystem);validateFallbackDirectory(home,filesystem);
  if(filesystem.exists(resolve(home,"auth.json")))throw new Error("OPENROUTER_CODEX_HOME_AUTH_PRESENT");
  const out:Record<string,string>={};for(const [key,value] of Object.entries(env))if(value!==undefined&&key.toLowerCase()!=="codex_home"&&FALLBACK_ALLOW.some(x=>x.toLowerCase()===key.toLowerCase()))out[key]=value;
  out.CODEX_HOME=home;return{environment:out,home};
}
export function fallbackEnvironment(env:NodeJS.ProcessEnv,isolation:FallbackIsolation={}):Record<string,string>{return prepareFallbackExecution(env,isolation).environment;}
export function openRouterConfig(){return {model_provider:"openrouter",model_providers:{openrouter:{name:"OpenRouter",base_url:"https://openrouter.ai/api/v1",env_key:"OPENROUTER_API_KEY",requires_openai_auth:false,wire_api:"responses",request_max_retries:0,stream_max_retries:0,supports_websockets:false}},agents:{enabled:false}} as const;}
export function threadReusable(state:any,providerMode:string,modelIdentity:string,role:string,worktree:string){return state?.schemaVersion===2&&state.providerMode===providerMode&&state.modelIdentity===modelIdentity&&state.role===role&&state.worktree===worktree;}
export function redact(value:string,secret:string|undefined){return secret?value.split(secret).join("[REDACTED]"):value;}
export interface ProvenanceOps{lock:string;planRecord:string;buildRecord:string;readPlan(status:"PROPOSED"|"APPROVED"):{canonical:string;hash:string};stateHash():string;execute():Promise<void>;write(path:string,value:unknown):void}
export async function runPlanProducer(modelId:string,ops:ProvenanceOps){const {acquireExecutionLock}=await import("@print-engineer/openrouter-free-selector");const release=acquireExecutionLock(ops.lock);try{let before:string|undefined;try{before=ops.readPlan("PROPOSED").hash;}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;before=undefined;}await ops.execute();const after=ops.readPlan("PROPOSED");if(before===after.hash)throw new Error("PLAN_ARTIFACT_UNCHANGED");const record:PlanProducer={schema_version:1,kind:"plan_producer",plan_path:after.canonical,plan_sha256:after.hash,model_id:modelId};ops.write(ops.planRecord,record);return record;}finally{release();}}
export async function runBuildProducer(modelId:string,ops:ProvenanceOps){const {acquireExecutionLock}=await import("@print-engineer/openrouter-free-selector");const release=acquireExecutionLock(ops.lock);try{const plan=ops.readPlan("APPROVED"),before=ops.stateHash();await ops.execute();const after=ops.stateHash();if(before===after)throw new Error("BUILD_STATE_UNCHANGED");const currentPlan=ops.readPlan("APPROVED");if(currentPlan.hash!==plan.hash)throw new Error("BUILD_PLAN_CHANGED");const record:BuildProducer={schema_version:1,kind:"build_producer",plan_path:plan.canonical,plan_sha256:plan.hash,worktree_state_sha256:after,model_id:modelId};ops.write(ops.buildRecord,record);return record;}finally{release();}}
export async function planReviewProducer(path:string,current:{canonical:string;hash:string}){const {loadProducer,validatePlanProducer}=await import("@print-engineer/openrouter-free-selector");const p=loadProducer(path,validatePlanProducer);if(p.plan_path!==current.canonical||p.plan_sha256!==current.hash)throw new Error("PLAN_PRODUCER_UNKNOWN");return p.model_id;}
export async function buildReviewProducer(path:string,currentPlan:{canonical:string;hash:string},stateHash:string){const {loadProducer,validateBuildProducer}=await import("@print-engineer/openrouter-free-selector");const p=loadProducer(path,validateBuildProducer);if(p.plan_path!==currentPlan.canonical||p.plan_sha256!==currentPlan.hash||p.worktree_state_sha256!==stateHash)throw new Error("BUILD_PRODUCER_UNKNOWN");return p.model_id;}
export async function defaultProvenanceOps(repo:string,planPath:string,paths:{lock:string;plan:string;build:string},execute:()=>Promise<void>,stateHash:()=>string):Promise<ProvenanceOps>{const {atomicWrite,readPlanArtifact}=await import("@print-engineer/openrouter-free-selector");return{lock:paths.lock,planRecord:paths.plan,buildRecord:paths.build,readPlan:s=>readPlanArtifact(repo,planPath,s),stateHash,execute,write:atomicWrite};}
export interface SelectionInput{phase:CodexPhase;reviewTarget?:ReviewTarget;key:string;fetcher:FetchLike;registryPath:string;plan?:{canonical:string;hash:string};planProducerPath?:string;buildProducerPath?:string;stateHash?:string;override?:string;now?:Date}
export async function selectOpenRouter(input:SelectionInput){const {fetchCatalog,loadRegistry,preflightExactModel,roleForPhase,selectFirstCompatibleEligible}=await import("@print-engineer/openrouter-free-selector");const role=roleForPhase(input.phase,input.reviewTarget);const excluded=new Set<string>();if(role==="plan-review"){if(!input.plan||!input.planProducerPath)throw new Error("PLAN_PRODUCER_UNKNOWN");excluded.add(await planReviewProducer(input.planProducerPath,input.plan));}if(role==="review"){if(!input.plan||!input.buildProducerPath||!input.stateHash)throw new Error("BUILD_PRODUCER_UNKNOWN");excluded.add(await buildReviewProducer(input.buildProducerPath,input.plan,input.stateHash));}const catalog=await fetchCatalog(input.fetcher,input.key,role);const entries=loadRegistry(input.registryPath);const selected=selectFirstCompatibleEligible(catalog,role,entries,excluded,input.override,input.now);await preflightExactModel(input.fetcher,input.key,selected.modelId,input.now);return{...selected,role,selectionMode:input.override?"override":"auto" as const};}
