import { readFileSync } from "node:fs";
export const COMPATIBILITY_SECONDS=2_592_000;
export const CODEX_SDK_VERSION="0.147.0";
export interface CompatibilityEntry {model_id:string;codex_sdk_version:string;provider_id:"openrouter";wire_api:"responses";validated_at:string;valid_until:string}
const TS=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;
function validSchema(e:unknown):e is CompatibilityEntry {if(!e||typeof e!=="object"||Array.isArray(e))return false;const x=e as any;if(Object.keys(x).sort().join()!==["codex_sdk_version","model_id","provider_id","validated_at","valid_until","wire_api"].sort().join())return false;if(typeof x.model_id!=="string"||!/^[^/,]+\/[^/,]+:free$/.test(x.model_id)||x.model_id==="openrouter/free"||x.model_id==="openrouter/auto"||x.codex_sdk_version!==CODEX_SDK_VERSION||x.provider_id!=="openrouter"||x.wire_api!=="responses"||!TS.test(x.validated_at)||!TS.test(x.valid_until))return false;const a=Date.parse(x.validated_at),b=Date.parse(x.valid_until);return Number.isFinite(a)&&Number.isFinite(b)&&new Date(a).toISOString()===x.validated_at&&new Date(b).toISOString()===x.valid_until&&b-a===COMPATIBILITY_SECONDS*1000;}
export function validateEntry(e:unknown,now=new Date()):e is CompatibilityEntry {if(!validSchema(e))return false;const x=e as CompatibilityEntry,a=Date.parse(x.validated_at),b=Date.parse(x.valid_until),n=now.getTime();return a<=n&&n<b;}
export function loadRegistry(path:string):CompatibilityEntry[]{let root:any;try{root=JSON.parse(readFileSync(path,"utf8"));}catch{throw new Error("COMPATIBILITY_REGISTRY_INVALID");}if(!root||typeof root!=="object"||Array.isArray(root)||root.schema_version!==1||!Array.isArray(root.entries)||Object.keys(root).sort().join()!=="entries,schema_version")throw new Error("COMPATIBILITY_REGISTRY_INVALID");const validated:CompatibilityEntry[]=[];const ids=new Set<string>();for(const entry of root.entries){if(!validSchema(entry))throw new Error("COMPATIBILITY_REGISTRY_INVALID");if(ids.has(entry.model_id))throw new Error("COMPATIBILITY_REGISTRY_INVALID");ids.add(entry.model_id);validated.push(entry);}return validated;}
export type CompatibilityStatus="current"|"unknown"|"stale";
export function compatibilityStatus(entries:CompatibilityEntry[],modelId:string,now=new Date()):CompatibilityStatus{const matching=entries.filter(e=>e.model_id===modelId);if(matching.length===0)return "unknown";const entry=matching[0];return validateEntry(entry,now)?"current":"stale";}
export function requireCompatibility(entries:unknown[],modelId:string,now=new Date()):CompatibilityEntry{const matching=entries.filter(e=>e&&typeof e==="object"&&!Array.isArray(e)&&(e as any).model_id===modelId&&(e as any).codex_sdk_version===CODEX_SDK_VERSION&&(e as any).provider_id==="openrouter"&&(e as any).wire_api==="responses");if(matching.length!==1)throw new Error("CODEX_COMPATIBILITY_UNKNOWN");if(!validateEntry(matching[0],now))throw new Error("CODEX_COMPATIBILITY_STALE");return matching[0];}
export function validityWindow(validatedAt:Date){return {validated_at:validatedAt.toISOString(),valid_until:new Date(validatedAt.getTime()+COMPATIBILITY_SECONDS*1000).toISOString()};}
