import {createHash,randomBytes} from "node:crypto";
import {closeSync,constants,existsSync,fsyncSync,lstatSync,mkdirSync,openSync,readFileSync,readlinkSync,realpathSync,renameSync,rmSync,writeFileSync} from "node:fs";
import {dirname,isAbsolute,relative,resolve} from "node:path";
import {execFileSync} from "node:child_process";
export const PROVENANCE_NAMESPACE="print-engineer/model-runner/selector-v1";
export type StatusRecord={status:string;destination:string;source?:string};
export type PlanProducer={schema_version:1;kind:"plan_producer";plan_path:string;plan_sha256:string;model_id:string};
export type BuildProducer={schema_version:1;kind:"build_producer";plan_path:string;plan_sha256:string;worktree_state_sha256:string;model_id:string};
export type ReadOnlyExecutionRecord={schema_version:1;kind:"readonly_execution";task_key:string;worktree_path:string;worktree_state_sha256:string;provider_id:"openrouter";model_id:string;phase:"general";role:"readonly";completed_at:string;success:true};
export function sha256(data:string|Buffer){return createHash("sha256").update(data).digest("hex");}
const decoder=new TextDecoder("utf-8",{fatal:true});const HEX=/^[0-9a-f]{64}$/;const MODEL=/^[^/,]+\/[^/,]+:free$/;
function u64(n:number){const b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(n));return b;}
function pathFrom(bytes:Buffer){let v:string;try{v=decoder.decode(bytes);}catch{throw new Error("WORKTREE_STATE_UNSUPPORTED");}if(!v||v.includes("\\")||v.startsWith("/")||/^[A-Za-z]:/.test(v)||v.split("/").some(p=>!p||p==="."||p===".."))throw new Error("WORKTREE_STATE_UNSUPPORTED");return v;}
function validStatus(xy:string){if(xy==="??")return true;if(xy.length!==2||xy.includes("U")||xy==="!!")return false;const a=new Set([" ","M","A","D","R","C"]);return a.has(xy[0])&&a.has(xy[1])&&xy!=="  ";}
export function parsePorcelainV1(raw:Buffer):StatusRecord[]{const out:StatusRecord[]=[],seen=new Set<string>();let p=0;while(p<raw.length){if(p+3>raw.length)throw new Error("WORKTREE_STATE_UNSUPPORTED");const status=raw.subarray(p,p+2).toString("ascii");if(raw[p+2]!==32||!validStatus(status))throw new Error("WORKTREE_STATE_UNSUPPORTED");p+=3;let z=raw.indexOf(0,p);if(z<0)throw new Error("WORKTREE_STATE_UNSUPPORTED");const destination=pathFrom(raw.subarray(p,z));p=z+1;let source:string|undefined;if(status.includes("R")||status.includes("C")){z=raw.indexOf(0,p);if(z<0)throw new Error("WORKTREE_STATE_UNSUPPORTED");source=pathFrom(raw.subarray(p,z));p=z+1;}if(seen.has(destination))throw new Error("WORKTREE_STATE_UNSUPPORTED");seen.add(destination);out.push({status,destination,source});}return out.sort((a,b)=>Buffer.compare(Buffer.from(a.destination),Buffer.from(b.destination))||Buffer.compare(Buffer.from(a.source??""),Buffer.from(b.source??""))||Buffer.compare(Buffer.from(a.status),Buffer.from(b.status)));}
export type WorktreeIo={status(repo:string):Buffer;lstat(path:string):{isSymbolicLink():boolean;isFile():boolean};readFile(path:string):Buffer;readlink(path:string):Buffer;exists(path:string):boolean};
const realIo:WorktreeIo={status:repo=>execFileSync("git",["status","--porcelain=v1","-z","--untracked-files=all"],{cwd:repo,encoding:"buffer",shell:false}),lstat:p=>lstatSync(p),readFile:p=>readFileSync(p),readlink:p=>readlinkSync(p,{encoding:"buffer"}),exists:p=>existsSync(p)};
export function computeWorktreeStateHash(repo:string,io:WorktreeIo=realIo){const records=parsePorcelainV1(io.status(repo));const parts:Buffer[]=[Buffer.from("print-engineer-worktree-state-v1\0","ascii"),u64(records.length)];for(const r of records){const d=Buffer.from(r.destination),s=Buffer.from(r.source??""),full=resolve(repo,...r.destination.split("/"));let marker="D";let payload:Buffer=Buffer.alloc(0);if(io.exists(full)){const st=io.lstat(full);if(st.isSymbolicLink()){marker="L";payload=Buffer.from(io.readlink(full));decoder.decode(payload);}else if(st.isFile()){marker="F";payload=Buffer.from(io.readFile(full));}else throw new Error("WORKTREE_STATE_UNSUPPORTED");}else if(!r.status.includes("D"))throw new Error("WORKTREE_STATE_UNSUPPORTED");parts.push(Buffer.from(r.status),u64(d.length),d,u64(s.length),s,Buffer.from(marker),u64(payload.length),payload);}return sha256(Buffer.concat(parts));}
export const worktreeStateHash=computeWorktreeStateHash;
function commonDir(repo:string){return execFileSync("git",["rev-parse","--path-format=absolute","--git-common-dir"],{cwd:repo,encoding:"utf8",shell:false}).trim();}
export function provenancePaths(repo:string,planPath:string){const root=resolve(commonDir(repo),...PROVENANCE_NAMESPACE.split("/")),key=sha256(Buffer.from(planPath));return{root,lock:resolve(root,"execution.lock"),plan:resolve(root,"plan-producers",`${key}.json`),build:resolve(root,"build-producers",`${key}.json`)};}
export function readonlyExecutionPaths(repo:string,taskKey:string,worktreePath:string){const root=resolve(commonDir(repo),...PROVENANCE_NAMESPACE.split("/"),"readonly-executions"),key=sha256(Buffer.from(`${taskKey}|${worktreePath}`));return{root,record:resolve(root,`${key}.json`)};}
function keys(v:any,k:string[]){return v&&typeof v==="object"&&!Array.isArray(v)&&Object.keys(v).join("|")===k.join("|");}
export function validatePlanProducer(v:unknown):v is PlanProducer{return keys(v,["schema_version","kind","plan_path","plan_sha256","model_id"])&&(v as any).schema_version===1&&(v as any).kind==="plan_producer"&&typeof (v as any).plan_path==="string"&&HEX.test((v as any).plan_sha256)&&MODEL.test((v as any).model_id);}
export function validateBuildProducer(v:unknown):v is BuildProducer{return keys(v,["schema_version","kind","plan_path","plan_sha256","worktree_state_sha256","model_id"])&&(v as any).schema_version===1&&(v as any).kind==="build_producer"&&typeof (v as any).plan_path==="string"&&HEX.test((v as any).plan_sha256)&&HEX.test((v as any).worktree_state_sha256)&&MODEL.test((v as any).model_id);}
export function validateReadOnlyExecutionRecord(v:unknown):v is ReadOnlyExecutionRecord{return keys(v,["schema_version","kind","task_key","worktree_path","worktree_state_sha256","provider_id","model_id","phase","role","completed_at","success"])&&(v as any).schema_version===1&&(v as any).kind==="readonly_execution"&&typeof (v as any).task_key==="string"&&typeof (v as any).worktree_path==="string"&&HEX.test((v as any).worktree_state_sha256)&&(v as any).provider_id==="openrouter"&&MODEL.test((v as any).model_id)&&(v as any).phase==="general"&&(v as any).role==="readonly"&&typeof (v as any).completed_at==="string"&&(v as any).success===true;}
export function loadProducer<T extends PlanProducer|BuildProducer>(path:string,validate:(v:unknown)=>v is T):T{const code=validate===validatePlanProducer?"PLAN_PRODUCER_UNKNOWN":"BUILD_PRODUCER_UNKNOWN";try{const st=lstatSync(path);if(!st.isFile()||st.isSymbolicLink())throw 0;const v=JSON.parse(readFileSync(path,"utf8"));if(!validate(v))throw 0;return v;}catch{throw new Error(code);}}
export function loadReadOnlyExecutionRecord(path:string):ReadOnlyExecutionRecord{try{const st=lstatSync(path);if(!st.isFile()||st.isSymbolicLink())throw 0;const v=JSON.parse(readFileSync(path,"utf8"));if(!validateReadOnlyExecutionRecord(v))throw 0;return v;}catch{throw new Error("READONLY_EXECUTION_RECORD_UNKNOWN");}}
function dirs(path:string){const missing:string[]=[];let current=path;while(!existsSync(current)){missing.push(current);const parent=dirname(current);if(parent===current)throw new Error("PROVENANCE_WRITE_FAILED");current=parent;}let st=lstatSync(current);if(!st.isDirectory()||st.isSymbolicLink())throw new Error("PROVENANCE_WRITE_FAILED");for(const item of missing.reverse()){mkdirSync(item,{mode:0o700});st=lstatSync(item);if(!st.isDirectory()||st.isSymbolicLink())throw new Error("PROVENANCE_WRITE_FAILED");}}
export function atomicWrite(path:string,value:unknown){dirs(dirname(path));const tmp=resolve(dirname(path),`.${randomBytes(16).toString("hex")}.tmp`);let fd:number|undefined;try{fd=openSync(tmp,constants.O_CREAT|constants.O_EXCL|constants.O_WRONLY,0o600);writeFileSync(fd,Buffer.from(JSON.stringify(value)));fsyncSync(fd);closeSync(fd);fd=undefined;renameSync(tmp,path);try{const directory=openSync(dirname(path),constants.O_RDONLY);try{fsyncSync(directory);}finally{closeSync(directory);}}catch{/* Best effort on platforms that cannot sync directories. */}}catch{if(fd!==undefined)closeSync(fd);rmSync(tmp,{force:true});throw new Error("PROVENANCE_WRITE_FAILED");}}
export function acquireExecutionLock(path:string){dirs(dirname(path));let fd:number;try{fd=openSync(path,"wx",0o600);}catch{throw new Error("SELECTOR_EXECUTION_LOCKED");}let done=false;return()=>{if(done)return;done=true;closeSync(fd);rmSync(path,{force:true});};}
export function withLock<T>(path:string,fn:()=>T){const release=acquireExecutionLock(path);try{return fn();}finally{release();}}
export function canonicalPlanPath(repo:string,path:string){if(!path||isAbsolute(path)||path.includes("\\")||path.split("/").some(p=>!p||p==="."||p==="..")||!path.startsWith("plans/")||!path.endsWith(".md"))throw new Error("INVALID_PLAN_PATH");const plans=realpathSync(resolve(repo,"plans")),full=resolve(repo,...path.split("/"));let existing=full;while(!existsSync(existing)){const parent=dirname(existing);if(parent===existing)throw new Error("INVALID_PLAN_PATH");existing=parent;}const canonicalExisting=realpathSync(existing),rel=relative(plans,canonicalExisting);if(rel.startsWith("..")||isAbsolute(rel))throw new Error("INVALID_PLAN_PATH");return path;}
export function readPlanArtifact(repo:string,path:string,status:"PROPOSED"|"APPROVED"){const canonical=canonicalPlanPath(repo,path),full=resolve(repo,...canonical.split("/")),st=lstatSync(full);if(!st.isFile()||st.isSymbolicLink()||st.size>262144)throw new Error("INVALID_PLAN_ARTIFACT");const bytes=readFileSync(full);if(bytes.subarray(0,3).equals(Buffer.from([239,187,191])))throw new Error("INVALID_PLAN_ARTIFACT");let text:string;try{text=decoder.decode(bytes);}catch{throw new Error("INVALID_PLAN_ARTIFACT");}const found=text.replace(/\r\n/g,"\n").split("\n").filter(x=>x.startsWith("Status:"));if(found.length!==1||found[0]!==`Status: ${status}`)throw new Error("INVALID_PLAN_ARTIFACT");return{canonical,bytes,hash:sha256(bytes)};}
