import test from "node:test";import assert from "node:assert/strict";import {readFileSync} from "node:fs";import {validityWindow} from "../src/index.js";import {selectFirstCompatibleEligible,selectFirstEligible,roleForPhase} from "../src/index.js";
import type {CompatibilityEntry} from "../src/index.js";
const m=(id:string,price="0")=>({id,pricing:{prompt:price,completion:"0",request:"0"},architecture:{input_modalities:["text"],output_modalities:["text"]},context_length:40000,top_provider:{context_length:40000},supported_parameters:["tools"]});
const now=new Date("2026-08-19T00:00:00.000Z");
const window=validityWindow(now);
const entry=(id:string):CompatibilityEntry=>({model_id:id,codex_sdk_version:"0.147.0",provider_id:"openrouter",wire_api:"responses",...window});
const expired=(id:string):CompatibilityEntry=>({model_id:id,codex_sdk_version:"0.147.0",provider_id:"openrouter",wire_api:"responses",validated_at:"2026-07-20T00:00:00.000Z",valid_until:"2026-08-19T00:00:00.000Z"});
test("server order first eligible and exclusions",()=>{assert.equal(selectFirstEligible([m("a/a:free","1"),m("b/b:free"),m("c/c:free")],"plan").modelId,"b/b:free");assert.equal(selectFirstEligible([m("b/b:free"),m("c/c:free")],"review",new Set(["b/b:free"])).modelId,"c/c:free")});
test("roles are exact",()=>{assert.equal(roleForPhase("review","plan"),"plan-review");assert.throws(()=>roleForPhase("review"))});
test("override remains subject to qualification and exclusion",()=>{assert.equal(selectFirstEligible([m("a/a:free"),m("b/b:free")],"build",new Set(),"b/b:free").modelId,"b/b:free");assert.throws(()=>selectFirstEligible([m("b/b:free")],"build",new Set(["b/b:free"]),"b/b:free"));assert.throws(()=>selectFirstEligible([m("b/b:free","1")],"build",new Set(),"b/b:free"));});

// Read-only selector role tests
test("roleForPhase general returns readonly",()=>{assert.equal(roleForPhase("general"),"readonly");});
test("readonly role uses server-ordered catalog",()=>{const catalog=[m("a/a:free","1"),m("b/b:free"),m("c/c:free")];assert.equal(selectFirstEligible(catalog,"readonly").modelId,"b/b:free");});
test("readonly role requires exact :free identity",()=>{const catalog=[m("invalid-format"),m("valid/model:free")];assert.equal(selectFirstEligible(catalog,"readonly").modelId,"valid/model:free");assert.throws(()=>selectFirstEligible([m("invalid-format")],"readonly"),/NO_VERIFIED_FREE_MODEL/);const clean=[m("valid/model:free")];assert.equal(selectFirstEligible(clean,"readonly").modelId,"valid/model:free");});
test("readonly role requires zero-cost qualification",()=>{const catalog=[m("a/a:free","1"),m("b/b:free")];assert.equal(selectFirstEligible(catalog,"readonly").modelId,"b/b:free");});
test("readonly role forbids openrouter/free and openrouter/auto",()=>{const catalog=[m("openrouter/free"),m("openrouter/auto"),m("valid/model:free")];assert.equal(selectFirstEligible(catalog,"readonly").modelId,"valid/model:free");});
test("readonly role has no producer exclusion",()=>{const catalog=[m("a/a:free"),m("b/b:free")];assert.equal(selectFirstEligible(catalog,"readonly",new Set(["a/a:free"])).modelId,"b/b:free");assert.equal(selectFirstEligible(catalog,"readonly").modelId,"a/a:free");});
test("PLAN BUILD REVIEW roles unchanged",()=>{assert.equal(roleForPhase("plan"),"plan");assert.equal(roleForPhase("build"),"build");assert.equal(roleForPhase("review","plan"),"plan-review");assert.equal(roleForPhase("review","implementation"),"review");});
// --- selectFirstCompatibleEligible: compatibility-gated eligibility ---
test("8. UNKNOWN A then CURRENT B -> B is selected (server order preserved)",()=>{const catalog=[m("a/a:free"),m("b/b:free")];const entries=[entry("b/b:free")];assert.equal(selectFirstCompatibleEligible(catalog,"plan",entries).modelId,"b/b:free");});
test("9. STALE A then CURRENT B -> B is selected",()=>{const catalog=[m("a/a:free"),m("b/b:free")];const entries=[expired("a/a:free"),entry("b/b:free")];assert.equal(selectFirstCompatibleEligible(catalog,"plan",entries).modelId,"b/b:free");});
test("10. unqualified A (non-zero-priced) then CURRENT B -> B selected",()=>{const catalog=[m("a/a:free","1"),m("b/b:free")];const entries=[entry("b/b:free")];assert.equal(selectFirstCompatibleEligible(catalog,"plan",entries).modelId,"b/b:free");});
test("11. excluded CURRENT A then CURRENT B -> B selected (exclusion honored)",()=>{const catalog=[m("a/a:free"),m("b/b:free")];const entries=[entry("a/a:free"),entry("b/b:free")];assert.equal(selectFirstCompatibleEligible(catalog,"plan",entries,new Set(["a/a:free"])).modelId,"b/b:free");});
test("12. single CURRENT model -> selected",()=>{const catalog=[m("a/a:free")];const entries=[entry("a/a:free")];assert.equal(selectFirstCompatibleEligible(catalog,"plan",entries).modelId,"a/a:free");});
test("13. zero fully-eligible candidates -> NO_CURRENT_COMPATIBLE_FREE_MODEL",()=>{const catalog=[m("a/a:free"),m("b/b:free")];const entries=[expired("a/a:free"),expired("b/b:free")];assert.throws(()=>selectFirstCompatibleEligible(catalog,"plan",entries),/NO_CURRENT_COMPATIBLE_FREE_MODEL/);assert.throws(()=>selectFirstCompatibleEligible([m("a/a:free","1")],"plan",[entry("a/a:free")]),/NO_CURRENT_COMPATIBLE_FREE_MODEL/);});
test("14. override CURRENT -> exact override (no fallthrough)",()=>{const catalog=[m("a/a:free"),m("b/b:free")];const entries=[entry("a/a:free"),entry("b/b:free")];assert.equal(selectFirstCompatibleEligible(catalog,"plan",entries,new Set(),"b/b:free").modelId,"b/b:free");});
test("15. override unknown -> CODEX_COMPATIBILITY_UNKNOWN with no fallthrough",()=>{const catalog=[m("a/a:free"),m("b/b:free")];const entries=[entry("a/a:free")];assert.throws(()=>selectFirstCompatibleEligible(catalog,"plan",entries,new Set(),"b/b:free"),/CODEX_COMPATIBILITY_UNKNOWN/);});
test("16. override stale -> CODEX_COMPATIBILITY_STALE with no fallthrough",()=>{const catalog=[m("a/a:free"),m("b/b:free")];const entries=[entry("a/a:free"),expired("b/b:free")];assert.throws(()=>selectFirstCompatibleEligible(catalog,"plan",entries,new Set(),"b/b:free"),/CODEX_COMPATIBILITY_STALE/);});
test("17. override not qualified -> NO_VERIFIED_FREE_MODEL and no fallthrough",()=>{const catalog=[m("a/a:free","1"),m("b/b:free")];const entries=[entry("a/a:free"),entry("b/b:free")];assert.throws(()=>selectFirstCompatibleEligible(catalog,"plan",entries,new Set(),"a/a:free"),/NO_VERIFIED_FREE_MODEL/);});
test("18. override excluded -> NO_VERIFIED_FREE_MODEL and no fallthrough",()=>{const catalog=[m("a/a:free"),m("b/b:free")];const entries=[entry("a/a:free"),entry("b/b:free")];assert.throws(()=>selectFirstCompatibleEligible(catalog,"plan",entries,new Set(["a/a:free"]),"a/a:free"),/NO_VERIFIED_FREE_MODEL/);});
test("19. server-order determinism (no sorting/scoring/randomness)",()=>{const catalog=[m("z/z:free"),m("a/a:free"),m("m/m:free")];const entries=[entry("z/z:free"),entry("a/a:free"),entry("m/m:free")];assert.equal(selectFirstCompatibleEligible(catalog,"plan",entries).modelId,"z/z:free");assert.equal(selectFirstCompatibleEligible(catalog,"plan",entries).modelId,"z/z:free");});
test("20. model-selector.ts has no Date.parse / window arithmetic in selection",()=>{const source=readFileSync(new URL("../../src/model-selector.ts",import.meta.url),"utf8");assert.equal(/Date\.parse/.test(source),false);assert.equal(/COMPATIBILITY_SECONDS/.test(source),false);assert.equal(/2_592_000|2592000/.test(source),false);});
test("21. role behavior unchanged across plan/build/plan-review/review/readonly",()=>{const catalog=[m("a/a:free"),m("b/b:free")];const entries=[entry("a/a:free"),entry("b/b:free")];for(const role of ["plan","build","plan-review","review","readonly"] as const){assert.equal(selectFirstCompatibleEligible(catalog,role,entries).modelId,"a/a:free");}});
test("22. strict zero pricing unchanged (non-zero candidate rejected before compatibility)",()=>{const catalog=[m("a/a:free","1"),m("b/b:free","0")];const entries=[entry("a/a:free"),entry("b/b:free")];assert.equal(selectFirstCompatibleEligible(catalog,"plan",entries).modelId,"b/b:free");});
test("23. exact :free + openrouter/free / openrouter/auto rejection unchanged",()=>{const catalog=[m("openrouter/free"),m("openrouter/auto"),m("vendor/x:free")];const entries=[entry("openrouter/free"),entry("openrouter/auto"),entry("vendor/x:free")];assert.equal(selectFirstCompatibleEligible(catalog,"plan",entries).modelId,"vendor/x:free");});
