import test from "node:test";import assert from "node:assert/strict";import {execFileSync} from "node:child_process";import {mkdirSync,mkdtempSync,readFileSync,rmSync,writeFileSync} from "node:fs";import {tmpdir} from "node:os";import {join} from "node:path";import {acquireExecutionLock,atomicWrite,canonicalPlanPath,computeWorktreeStateHash,parsePorcelainV1,sha256,validateBuildProducer,validatePlanProducer,validateReadOnlyExecutionRecord,readonlyExecutionPaths,ReadOnlyExecutionRecord} from "../src/index.js";
test("hash is deterministic",()=>{assert.equal(sha256("state"),sha256(Buffer.from("state")));assert.equal(sha256("state").length,64)});
const io=(status:string,files:Record<string,{kind:"file"|"link";data:string|Buffer}>)=>({status:()=>Buffer.from(status),exists:(p:string)=>Object.keys(files).some(k=>p.endsWith(k)),lstat:(p:string)=>{const x=Object.entries(files).find(([k])=>p.endsWith(k))?.[1];return{isFile:()=>x?.kind==="file",isSymbolicLink:()=>x?.kind==="link"}},readFile:(p:string)=>Buffer.from(Object.entries(files).find(([k])=>p.endsWith(k))![1].data),readlink:(p:string)=>Buffer.from(Object.entries(files).find(([k])=>p.endsWith(k))![1].data)});
test("canonical worktree hash is ordered and content-sensitive",()=>{const a=computeWorktreeStateHash("R",io("?? b.bin\0 M a.txt\0",{"a.txt":{kind:"file",data:"a"},"b.bin":{kind:"file",data:Buffer.from([0,255])}}));const b=computeWorktreeStateHash("R",io(" M a.txt\0?? b.bin\0",{"a.txt":{kind:"file",data:"a"},"b.bin":{kind:"file",data:Buffer.from([0,255])}}));assert.equal(a,b);assert.notEqual(a,computeWorktreeStateHash("R",io(" M a.txt\0?? b.bin\0",{"a.txt":{kind:"file",data:"changed"},"b.bin":{kind:"file",data:Buffer.from([0,255])}})))});
test("deletion rename symlink and ignored omission are represented",()=>{assert.equal(parsePorcelainV1(Buffer.from("R  new.txt\0old.txt\0 D gone.txt\0")).length,2);const link=computeWorktreeStateHash("R",io("?? link\0",{link:{kind:"link",data:"target"}}));assert.notEqual(link,computeWorktreeStateHash("R",io("?? link\0",{link:{kind:"link",data:"other"}})));const clean=computeWorktreeStateHash("R",io("",{}));assert.equal(clean,computeWorktreeStateHash("R",io("",{"ignored.local":{kind:"file",data:"synthetic"}})))});
test("unsupported porcelain fails closed",()=>{for(const raw of ["UU conflict\0","!! ignored\0","?? ../escape\0","?? dup\0?? dup\0","R  only-destination\0"])assert.throws(()=>parsePorcelainV1(Buffer.from(raw)),/WORKTREE_STATE_UNSUPPORTED/)});
test("canonical producer schemas reject extras",()=>{const p={schema_version:1,kind:"plan_producer",plan_path:"plans/x.md",plan_sha256:"a".repeat(64),model_id:"v/m:free"};assert.equal(validatePlanProducer(p),true);assert.equal(validatePlanProducer({...p,extra:true}),false);const b={schema_version:1,kind:"build_producer",plan_path:"plans/x.md",plan_sha256:"a".repeat(64),worktree_state_sha256:"b".repeat(64),model_id:"v/m:free"};assert.equal(validateBuildProducer(b),true)});
test("atomic write and exclusive lock",()=>{const root=mkdtempSync(join(tmpdir(),"selector-provenance-"));try{const path=join(root,"nested","record.json");atomicWrite(path,{ok:true});assert.equal(readFileSync(path,"utf8"),'{"ok":true}');const lock=join(root,"execution.lock"),release=acquireExecutionLock(lock);assert.throws(()=>acquireExecutionLock(lock),/SELECTOR_EXECUTION_LOCKED/);release();const again=acquireExecutionLock(lock);again();}finally{rmSync(root,{recursive:true,force:true})}});
test("plan path is canonical, contained, and prospective-safe",()=>{const root=mkdtempSync(join(tmpdir(),"plan-path-"));try{mkdirSync(join(root,"plans","nested"),{recursive:true});assert.equal(canonicalPlanPath(root,"plans/nested/new.md"),"plans/nested/new.md");for(const path of ["../x.md","plans/../x.md","plans/x.txt","C:/x.md","plans\\x.md"])assert.throws(()=>canonicalPlanPath(root,path),/INVALID_PLAN_PATH/)}finally{rmSync(root,{recursive:true,force:true})}});

// Read-only execution provenance tests
function initGitRepo(dir:string){execFileSync("git",["init","-q"],{cwd:dir});writeFileSync(join(dir,".git","info","exclude"),"");}
test("ReadOnlyExecutionRecord schema validation",()=>{const valid:ReadOnlyExecutionRecord={schema_version:1,kind:"readonly_execution",task_key:"task-1",worktree_path:"/tmp/worktree",worktree_state_sha256:"a".repeat(64),provider_id:"openrouter",model_id:"vendor/model:free",phase:"general",role:"readonly",completed_at:new Date().toISOString(),success:true};assert.equal(validateReadOnlyExecutionRecord(valid),true);assert.equal(validateReadOnlyExecutionRecord({...valid,extra:true}),false);assert.equal(validateReadOnlyExecutionRecord({...valid,schema_version:2}),false);assert.equal(validateReadOnlyExecutionRecord({...valid,kind:"plan_producer"}),false);assert.equal(validateReadOnlyExecutionRecord({...valid,provider_id:"primary"}),false);assert.equal(validateReadOnlyExecutionRecord({...valid,model_id:"invalid"}),false);assert.equal(validateReadOnlyExecutionRecord({...valid,phase:"plan"}),false);assert.equal(validateReadOnlyExecutionRecord({...valid,role:"plan"}),false);assert.equal(validateReadOnlyExecutionRecord({...valid,success:false}),false);assert.equal(validateReadOnlyExecutionRecord({...valid,worktree_state_sha256:"not-hex"}),false);});
test("readonlyExecutionPaths deterministic filename from task_key + worktree_path",()=>{const root=mkdtempSync(join(tmpdir(),"readonly-paths-"));try{initGitRepo(root);const paths1=readonlyExecutionPaths(root,"task-1",root);const paths2=readonlyExecutionPaths(root,"task-1",root);assert.equal(paths1.record,paths2.record);const paths3=readonlyExecutionPaths(root,"task-2",root);assert.notEqual(paths1.record,paths3.record);const paths4=readonlyExecutionPaths(root,"task-1","/different/path");assert.notEqual(paths1.record,paths4.record);}finally{rmSync(root,{recursive:true,force:true})}});
test("readonlyExecutionPaths uses atomicWrite convention",()=>{const root=mkdtempSync(join(tmpdir(),"readonly-atomic-"));try{initGitRepo(root);const paths=readonlyExecutionPaths(root,"task-1",root);atomicWrite(paths.record,{schema_version:1,kind:"readonly_execution",task_key:"task-1",worktree_path:root,worktree_state_sha256:"a".repeat(64),provider_id:"openrouter",model_id:"vendor/model:free",phase:"general",role:"readonly",completed_at:new Date().toISOString(),success:true});const content=readFileSync(paths.record,"utf8");assert.ok(content.includes("readonly_execution"));assert.ok(content.includes("vendor/model:free"));}finally{rmSync(root,{recursive:true,force:true})}});
test("readonlyExecutionRecord contains no forbidden fields",()=>{const record:ReadOnlyExecutionRecord={schema_version:1,kind:"readonly_execution",task_key:"task-1",worktree_path:"/tmp/worktree",worktree_state_sha256:"a".repeat(64),provider_id:"openrouter",model_id:"vendor/model:free",phase:"general",role:"readonly",completed_at:new Date().toISOString(),success:true};const keys=Object.keys(record);assert.ok(!keys.includes("prompt"));assert.ok(!keys.includes("response"));assert.ok(!keys.includes("stdout"));assert.ok(!keys.includes("stderr"));assert.ok(!keys.includes("secret"));assert.ok(!keys.includes("header"));assert.ok(!keys.includes("env"));assert.ok(!keys.includes("error"));assert.ok(!keys.includes("AGENTS.md"));});
test("readonlyExecutionPaths namespace/path conventions preserved",()=>{const root=mkdtempSync(join(tmpdir(),"readonly-namespace-"));try{initGitRepo(root);const paths=readonlyExecutionPaths(root,"task-1",root);const normalizedRecord=paths.record.replace(/\\/g,"/");const normalizedRoot=paths.root.replace(/\\/g,"/");assert.ok(normalizedRecord.includes("print-engineer/model-runner/selector-v1/readonly-executions"));assert.ok(normalizedRoot.includes("print-engineer/model-runner/selector-v1/readonly-executions"));}finally{rmSync(root,{recursive:true,force:true})}});
