import test from "node:test";import assert from "node:assert/strict";import {mkdirSync,mkdtempSync,readFileSync,rmSync} from "node:fs";import {tmpdir} from "node:os";import {join} from "node:path";import {acquireExecutionLock,atomicWrite,canonicalPlanPath,computeWorktreeStateHash,parsePorcelainV1,sha256,validateBuildProducer,validatePlanProducer} from "../src/index.js";
test("hash is deterministic",()=>{assert.equal(sha256("state"),sha256(Buffer.from("state")));assert.equal(sha256("state").length,64)});
const io=(status:string,files:Record<string,{kind:"file"|"link";data:string|Buffer}>)=>({status:()=>Buffer.from(status),exists:(p:string)=>Object.keys(files).some(k=>p.endsWith(k)),lstat:(p:string)=>{const x=Object.entries(files).find(([k])=>p.endsWith(k))?.[1];return{isFile:()=>x?.kind==="file",isSymbolicLink:()=>x?.kind==="link"}},readFile:(p:string)=>Buffer.from(Object.entries(files).find(([k])=>p.endsWith(k))![1].data),readlink:(p:string)=>Buffer.from(Object.entries(files).find(([k])=>p.endsWith(k))![1].data)});
test("canonical worktree hash is ordered and content-sensitive",()=>{const a=computeWorktreeStateHash("R",io("?? b.bin\0 M a.txt\0",{"a.txt":{kind:"file",data:"a"},"b.bin":{kind:"file",data:Buffer.from([0,255])}}));const b=computeWorktreeStateHash("R",io(" M a.txt\0?? b.bin\0",{"a.txt":{kind:"file",data:"a"},"b.bin":{kind:"file",data:Buffer.from([0,255])}}));assert.equal(a,b);assert.notEqual(a,computeWorktreeStateHash("R",io(" M a.txt\0?? b.bin\0",{"a.txt":{kind:"file",data:"changed"},"b.bin":{kind:"file",data:Buffer.from([0,255])}})))});
test("deletion rename symlink and ignored omission are represented",()=>{assert.equal(parsePorcelainV1(Buffer.from("R  new.txt\0old.txt\0 D gone.txt\0")).length,2);const link=computeWorktreeStateHash("R",io("?? link\0",{link:{kind:"link",data:"target"}}));assert.notEqual(link,computeWorktreeStateHash("R",io("?? link\0",{link:{kind:"link",data:"other"}})));const clean=computeWorktreeStateHash("R",io("",{}));assert.equal(clean,computeWorktreeStateHash("R",io("",{"ignored.local":{kind:"file",data:"synthetic"}})))});
test("unsupported porcelain fails closed",()=>{for(const raw of ["UU conflict\0","!! ignored\0","?? ../escape\0","?? dup\0?? dup\0","R  only-destination\0"])assert.throws(()=>parsePorcelainV1(Buffer.from(raw)),/WORKTREE_STATE_UNSUPPORTED/)});
test("canonical producer schemas reject extras",()=>{const p={schema_version:1,kind:"plan_producer",plan_path:"plans/x.md",plan_sha256:"a".repeat(64),model_id:"v/m:free"};assert.equal(validatePlanProducer(p),true);assert.equal(validatePlanProducer({...p,extra:true}),false);const b={schema_version:1,kind:"build_producer",plan_path:"plans/x.md",plan_sha256:"a".repeat(64),worktree_state_sha256:"b".repeat(64),model_id:"v/m:free"};assert.equal(validateBuildProducer(b),true)});
test("atomic write and exclusive lock",()=>{const root=mkdtempSync(join(tmpdir(),"selector-provenance-"));try{const path=join(root,"nested","record.json");atomicWrite(path,{ok:true});assert.equal(readFileSync(path,"utf8"),'{"ok":true}');const lock=join(root,"execution.lock"),release=acquireExecutionLock(lock);assert.throws(()=>acquireExecutionLock(lock),/SELECTOR_EXECUTION_LOCKED/);release();const again=acquireExecutionLock(lock);again();}finally{rmSync(root,{recursive:true,force:true})}});
test("plan path is canonical, contained, and prospective-safe",()=>{const root=mkdtempSync(join(tmpdir(),"plan-path-"));try{mkdirSync(join(root,"plans","nested"),{recursive:true});assert.equal(canonicalPlanPath(root,"plans/nested/new.md"),"plans/nested/new.md");for(const path of ["../x.md","plans/../x.md","plans/x.txt","C:/x.md","plans\\x.md"])assert.throws(()=>canonicalPlanPath(root,path),/INVALID_PLAN_PATH/)}finally{rmSync(root,{recursive:true,force:true})}});
