"""Tests for G-code and .gcode.3mf slice-statistics parsing."""

from __future__ import annotations

import json
import zipfile
from pathlib import Path

import pytest

from print_engineer.adapters.slicer.gcode import parse_duration, parse_gcode, parse_gcode_3mf

SAMPLE_GCODE = """\
; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.2 on 2026-08-14 at 23:21:14
; model printing time: 28m 31s; total estimated time: 28m 33s
; estimated first layer printing time (normal mode) = 1s
; total layer number: 100
; model label id: 15
; filament_density: 1.24
; filament_diameter: 1.75
; max_z_height: 20.00
; filament: 1
; HEADER_BLOCK_END

; CONFIG_BLOCK_START
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 3
; CONFIG_BLOCK_END

; EXECUTABLE_BLOCK_START
G1 X0 Y0 Z0.2
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 1321.15
; filament used [cm3] = 3.18
"""

SAMPLE_GCODE_MULTI = """\
; HEADER_BLOCK_START
; model printing time: 1h 2m 3s
; total layer number: 200
; filament_density: 0
; max_z_height: 45.5
; HEADER_BLOCK_END

; filament used [mm] = 100.0
; filament used [cm3] = 0.5
; filament used [mm] = 200.0
; filament used [cm3] = 0.75
"""


def test_parse_duration() -> None:
    assert parse_duration("28m 31s") == pytest.approx(28 + 31 / 60)
    assert parse_duration("1h 2m 3s") == pytest.approx(62 + 3 / 60)
    assert parse_duration("45s") == pytest.approx(0.75)
    assert parse_duration("0m 3s") == pytest.approx(0.05)
    assert parse_duration("") == 0.0


def test_parse_gcode_extracts_stats(tmp_path: Path) -> None:
    path = tmp_path / "plate_1.gcode"
    path.write_text(SAMPLE_GCODE, encoding="utf-8")
    stats = parse_gcode(path)
    assert stats["time_minutes"] == pytest.approx(28 + 31 / 60)
    assert stats["layer_count"] == 100
    assert stats["max_z_height"] == pytest.approx(20.0)
    assert stats["filament_used_mm"] == pytest.approx(1321.15)
    assert stats["filament_used_cm3"] == pytest.approx(3.18)
    assert stats["filament_density"] == pytest.approx(1.24)


def test_parse_gcode_sums_multiple_extruders(tmp_path: Path) -> None:
    path = tmp_path / "plate_1.gcode"
    path.write_text(SAMPLE_GCODE_MULTI, encoding="utf-8")
    stats = parse_gcode(path)
    assert stats["time_minutes"] == pytest.approx(62 + 3 / 60)
    assert stats["layer_count"] == 200
    assert stats["filament_used_mm"] == pytest.approx(300.0)
    assert stats["filament_used_cm3"] == pytest.approx(1.25)
    assert stats["max_z_height"] == pytest.approx(45.5)
    assert stats["filament_density"] == 0.0


def test_parse_gcode_missing_values(tmp_path: Path) -> None:
    path = tmp_path / "plate_1.gcode"
    path.write_text("G1 X0\n", encoding="utf-8")
    stats = parse_gcode(path)
    assert stats["time_minutes"] is None
    assert stats["layer_count"] is None
    assert stats["filament_used_mm"] is None


def _write_gcode_3mf(path: Path, *, prediction: int, used_m: str, used_g: str) -> None:
    slice_info = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<config><plate>"
        f'<metadata key="prediction" value="{prediction}"/>'
        f'<metadata key="weight" value=""/>'
        f'<filament id="1" type="PLA" used_m="{used_m}" used_g="{used_g}"/>'
        "</plate></config>\n"
    )
    plate_json = json.dumps(
        {
            "layer_height": 0.2,
            "nozzle_diameter": 0.4,
            "bed_type": "cool_plate",
            "version": 2,
        }
    )
    with zipfile.ZipFile(path, "w") as archive:
        archive.writestr("Metadata/slice_info.config", slice_info)
        archive.writestr("Metadata/plate_1.json", plate_json)


def test_parse_gcode_3mf(tmp_path: Path) -> None:
    path = tmp_path / "cube.gcode.3mf"
    _write_gcode_3mf(path, prediction=1713, used_m="1.32", used_g="0.00")
    meta = parse_gcode_3mf(path)
    assert meta["prediction_seconds"] == 1713
    assert meta["filament_used_m"] == pytest.approx(1.32)
    assert meta["filament_used_g"] == 0.0
    assert meta["layer_height"] == pytest.approx(0.2)
    assert meta["nozzle_diameter"] == pytest.approx(0.4)
    assert meta["bed_type"] == "cool_plate"


def test_parse_gcode_3mf_not_a_zip(tmp_path: Path) -> None:
    path = tmp_path / "broken.gcode.3mf"
    path.write_bytes(b"not a zip")
    assert parse_gcode_3mf(path) == {}
