"""Hermetic unit tests for OrcaSlicerAdapter (no real slicer invoked)."""

from __future__ import annotations

import json
import zipfile
from pathlib import Path

import pytest

from print_engineer.adapters.slicer.orca import OrcaSlicerAdapter
from print_engineer.adapters.slicer.process import ProcResult
from print_engineer.core.types import ProfileInfo, ProfileKind, ProfileSource, SliceJob
from print_engineer.errors import (
    InvalidModel,
    InvalidProfile,
    SliceFailed,
    SlicerNotInstalled,
    SliceTimeout,
    VersionMismatch,
)

SAMPLE_GCODE = """\
; HEADER_BLOCK_START
; generated by OrcaSlicer 9.9.9 on 2026-08-15 at 00:00:00
; model printing time: 28m 31s; total estimated time: 28m 33s
; total layer number: 100
; filament_density: 1.24
; max_z_height: 20.00
; HEADER_BLOCK_END

; EXECUTABLE_BLOCK_END

; filament used [mm] = 1321.15
; filament used [cm3] = 3.18
"""


def _fake_orca(tmp_path: Path, version: str = "9.9.9") -> Path:
    exe = tmp_path / "orca-slicer.exe"
    exe.write_bytes(b"MZ fake exe")
    (tmp_path / "OrcaSlicer.dll").write_bytes(
        f"\x00OrcaSlicer {version}\x00".encode()
    )
    return exe


def _adapter(tmp_path: Path, *, version: str = "9.9.9") -> OrcaSlicerAdapter:
    exe = _fake_orca(tmp_path, version)
    return OrcaSlicerAdapter(
        executable=exe,
        workdir=tmp_path / "workspace",
        timeout_seconds=30.0,
    )


def _profiles() -> tuple[ProfileInfo, ProfileInfo, ProfileInfo]:
    machine = ProfileInfo(
        name="Base 0.4 nozzle",
        kind=ProfileKind.PRINTER,
        content='{"type": "machine", "name": "Base 0.4 nozzle", "from": "system"}',
        source=ProfileSource.GENERATED,
        materialized=True,
    )
    process = ProfileInfo(
        name="Standard 0.20",
        kind=ProfileKind.PROCESS,
        content='{"type": "process", "name": "Standard 0.20", "from": "system"}',
        source=ProfileSource.GENERATED,
        compatible_printers=("Base 0.4 nozzle",),
        materialized=True,
    )
    filament = ProfileInfo(
        name="Generic PLA",
        kind=ProfileKind.FILAMENT,
        content='{"type": "filament", "name": "Generic PLA", "from": "system"}',
        source=ProfileSource.GENERATED,
        compatible_printers=("Base 0.4 nozzle",),
        materialized=True,
    )
    return process, filament, machine


def _job(tmp_path: Path, *, with_printer: bool = True) -> SliceJob:
    model = tmp_path / "cube.stl"
    model.write_text("solid cube\nendsolid cube\n", encoding="utf-8")
    process, filament, machine = _profiles()
    return SliceJob(
        model_path=model,
        profile=process,
        filament=filament,
        printer=machine if with_printer else None,
        timeout_seconds=30.0,
    )


def _write_gcode_3mf(path: Path) -> None:
    slice_info = (
        '<?xml version="1.0"?>\n<config><plate>'
        '<metadata key="prediction" value="1713"/>'
        '<metadata key="weight" value=""/>'
        '<filament id="1" type="PLA" used_m="1.32" used_g="0.00"/>'
        "</plate></config>\n"
    )
    with zipfile.ZipFile(path, "w") as archive:
        archive.writestr("Metadata/slice_info.config", slice_info)


def _write_project_3mf(path: Path, version: str) -> None:
    with zipfile.ZipFile(path, "w") as archive:
        archive.writestr(
            "Metadata/project_settings.config",
            json.dumps({"type": "project", "version": version}),
        )


def test_detect_returns_info(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    monkeypatch.setattr(
        "print_engineer.adapters.slicer.version.registry_display_version", lambda name: None
    )
    adapter = _adapter(tmp_path)
    info = adapter.detect()
    assert info is not None
    assert info.kind.value == "orca_slicer"
    assert info.version == "9.9.9"
    assert info.version_source == "binary"
    assert info.slicing_supported is True


def test_detect_missing_returns_none(tmp_path: Path) -> None:
    adapter = OrcaSlicerAdapter(
        executable=tmp_path / "missing.exe", workdir=tmp_path / "ws"
    )
    assert adapter.detect() is None


def test_slice_not_installed_raises(tmp_path: Path) -> None:
    adapter = OrcaSlicerAdapter(
        executable=tmp_path / "missing.exe", workdir=tmp_path / "ws"
    )
    with pytest.raises(SlicerNotInstalled):
        adapter.slice(_job(tmp_path))


def test_validate_input_missing_model_raises(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.setattr(
        "print_engineer.adapters.slicer.version.registry_display_version", lambda name: None
    )
    adapter = _adapter(tmp_path)
    with pytest.raises(InvalidModel):
        adapter.validate_input(tmp_path / "nope.stl")


def test_validate_input_bad_suffix_raises(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.setattr(
        "print_engineer.adapters.slicer.version.registry_display_version", lambda name: None
    )
    adapter = _adapter(tmp_path)
    bad = tmp_path / "cube.txt"
    bad.write_text("hi", encoding="utf-8")
    with pytest.raises(InvalidModel):
        adapter.validate_input(bad)


def test_validate_input_parses_info_output(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.setattr(
        "print_engineer.adapters.slicer.version.registry_display_version", lambda name: None
    )
    adapter = _adapter(tmp_path)
    model = tmp_path / "cube.stl"
    model.write_text("solid cube\nendsolid cube\n", encoding="utf-8")

    info_output = """\
[cube.stl]
size_x = 20.000000
size_y = 20.000000
size_z = 20.000000
number_of_facets = 12
manifold = yes
number_of_parts =  1
volume = 8000.000488
"""

    def fake_run(cmd: list[str], *, timeout: float) -> ProcResult:
        assert "--info" in cmd
        return ProcResult(
            stdout=info_output,
            stderr="",
            return_code=0,
            timed_out=False,
            killed=False,
            duration_seconds=0.1,
        )

    monkeypatch.setattr("print_engineer.adapters.slicer.base.run_cli", fake_run)
    validation = adapter.validate_input(model)
    assert validation.is_valid
    assert validation.size == (20.0, 20.0, 20.0)
    assert validation.volume_mm3 == pytest.approx(8000.000488)
    assert validation.facets == 12
    assert validation.is_manifold is True


def test_validate_input_rejected_by_slicer(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.setattr(
        "print_engineer.adapters.slicer.version.registry_display_version", lambda name: None
    )
    adapter = _adapter(tmp_path)
    model = tmp_path / "cube.stl"
    model.write_text("solid cube\nendsolid cube\n", encoding="utf-8")

    def fake_run(cmd: list[str], *, timeout: float) -> ProcResult:
        return ProcResult(
            stdout="",
            stderr="Slic3r::CLI::run found error, exit",
            return_code=1,
            timed_out=False,
            killed=False,
            duration_seconds=0.1,
        )

    monkeypatch.setattr("print_engineer.adapters.slicer.base.run_cli", fake_run)
    validation = adapter.validate_input(model)
    assert not validation.is_valid
    assert "rejected" in validation.message


def test_slice_success_parses_all_stats(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.setattr(
        "print_engineer.adapters.slicer.version.registry_display_version", lambda name: None
    )
    adapter = _adapter(tmp_path)
    job = _job(tmp_path)

    def fake_run(cmd: list[str], *, timeout: float, cwd: Path | None = None) -> ProcResult:
        assert cwd is not None
        job_dir = Path(cwd)
        (job_dir / "plate_1.gcode").write_text(SAMPLE_GCODE, encoding="utf-8")
        _write_gcode_3mf(job_dir / "cube.gcode.3mf")
        return ProcResult(
            stdout="",
            stderr="",
            return_code=0,
            timed_out=False,
            killed=False,
            duration_seconds=1.5,
        )

    monkeypatch.setattr("print_engineer.adapters.slicer.orca.run_cli", fake_run)
    result = adapter.slice(job)

    assert result.gcode_path is not None
    assert result.gcode_path.is_file()
    assert result.output_3mf is not None
    assert result.output_3mf.is_file()
    assert result.estimated_time_minutes == pytest.approx(28 + 31 / 60)
    assert result.layer_count == 100
    assert result.max_z_height == pytest.approx(20.0)
    assert result.filament_used_mm == pytest.approx(1321.15)
    assert result.filament_used_cm3 == pytest.approx(3.18)
    assert result.filament_density == pytest.approx(1.24)
    assert result.filament_weight_g == pytest.approx(1.24 * 3.18)
    assert result.return_code == 0
    assert tmp_path / "workspace" in result.gcode_path.parents


def test_slice_timeout_raises(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    monkeypatch.setattr(
        "print_engineer.adapters.slicer.version.registry_display_version", lambda name: None
    )
    adapter = _adapter(tmp_path)
    job = _job(tmp_path)

    def fake_run(cmd: list[str], *, timeout: float, cwd: Path | None = None) -> ProcResult:
        return ProcResult(
            stdout="",
            stderr="",
            return_code=None,
            timed_out=True,
            killed=True,
            duration_seconds=30.0,
        )

    monkeypatch.setattr("print_engineer.adapters.slicer.orca.run_cli", fake_run)
    with pytest.raises(SliceTimeout) as excinfo:
        adapter.slice(job)
    assert excinfo.value.to_dict()["details"]["timeout_seconds"] == 30.0


def test_slice_no_artifacts_raises(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    monkeypatch.setattr(
        "print_engineer.adapters.slicer.version.registry_display_version", lambda name: None
    )
    adapter = _adapter(tmp_path)
    job = _job(tmp_path)

    def fake_run(cmd: list[str], *, timeout: float, cwd: Path | None = None) -> ProcResult:
        return ProcResult(
            stdout="",
            stderr="Slic3r::CLI::run found error, exit",
            return_code=1,
            timed_out=False,
            killed=False,
            duration_seconds=3.0,
        )

    monkeypatch.setattr("print_engineer.adapters.slicer.orca.run_cli", fake_run)
    with pytest.raises(SliceFailed) as excinfo:
        adapter.slice(job)
    assert excinfo.value.to_dict()["details"]["return_code"] == 1


def test_slice_version_mismatch_raises(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.setattr(
        "print_engineer.adapters.slicer.version.registry_display_version", lambda name: None
    )
    adapter = _adapter(tmp_path, version="2.3.2")
    project = tmp_path / "project.3mf"
    _write_project_3mf(project, "02.07.01.62")
    job = _job(tmp_path)
    job = SliceJob(
        model_path=project,
        profile=job.profile,
        filament=job.filament,
        printer=job.printer,
        timeout_seconds=30.0,
    )
    with pytest.raises(VersionMismatch) as excinfo:
        adapter.slice(job)
    details = excinfo.value.to_dict()["details"]
    assert details["model_version"] == "02.07.01.62"
    assert details["slicer_version"] == "2.3.2"


def test_slice_missing_printer_profile_raises(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.setattr(
        "print_engineer.adapters.slicer.version.registry_display_version", lambda name: None
    )
    adapter = _adapter(tmp_path)
    with pytest.raises(InvalidProfile):
        adapter.slice(_job(tmp_path, with_printer=False))


def test_slice_incompatible_process_raises(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.setattr(
        "print_engineer.adapters.slicer.version.registry_display_version", lambda name: None
    )
    adapter = _adapter(tmp_path)
    job = _job(tmp_path)
    incompatible = ProfileInfo(
        name="Wrong Machine 0.6",
        kind=ProfileKind.PROCESS,
        content='{"type": "process", "name": "Wrong Machine 0.6"}',
        source=ProfileSource.GENERATED,
        compatible_printers=("Other Machine 0.6 nozzle",),
        materialized=True,
    )
    job = SliceJob(
        model_path=job.model_path,
        profile=incompatible,
        filament=job.filament,
        printer=job.printer,
        timeout_seconds=30.0,
    )
    with pytest.raises(InvalidProfile) as excinfo:
        adapter.slice(job)
    assert "not compatible" in excinfo.value.to_dict()["message"]
