import test from "node:test";import assert from "node:assert/strict";import {EventEmitter} from "node:events";import {PassThrough,Writable} from "node:stream";import {INITIALIZE_REQUEST,INITIALIZED_NOTIFICATION,readPrimaryStatus} from "../src/codex-app-server-client.js";
const account={account:{type:"chatgpt",planType:"plus"},requiresOpenaiAuth:true};const rate={rateLimitsByLimitId:null,rateLimits:{limitId:"codex",rateLimitReachedType:null,spendControlReached:false,primary:{usedPercent:1},secondary:null}};const sol={id:"gpt-5.6-sol",model:"gpt-5.6-sol",inputModalities:["text"]};
function fake(respond:(message:any,writes:any[])=>unknown){const child:any=new EventEmitter();child.stdout=new PassThrough();child.stderr=new PassThrough();child.killed=false;const writes:any[]=[];let spawned:any[]=[];child.kill=()=>{child.killed=true;queueMicrotask(()=>child.emit("exit",1));return true};child.stdin=new Writable({write(chunk,_e,done){const message=JSON.parse(String(chunk));writes.push(message);const response=respond(message,writes);if(response!==undefined){const values=Array.isArray(response)?response:[response];for(const value of values)child.stdout.write(typeof value==="string"?value+"\n":JSON.stringify(value)+"\n");}done();},final(done){queueMicrotask(()=>child.emit("exit",0));done();}});return{child,writes,get spawned(){return spawned},spawn:(...args:any[])=>{spawned=args;return child as any}};}
function success(message:any){if(message.method==="initialize")return{id:1,result:{userAgent:"codex_cli_rs/0.147.0",codexHome:"C:\\Users\\test\\.codex",platformFamily:"windows",platformOs:"windows"}};if(message.method==="account/read")return{id:2,result:account};if(message.method==="account/rateLimits/read")return{id:3,result:rate};if(message.method==="model/list")return{id:message.id,result:{data:[sol],nextCursor:null}};}
test("exact headerless initialize envelope and ordered successful flow",async()=>{const f=fake(success);const pending=readPrimaryStatus(f.spawn);assert.deepEqual(f.writes[0],INITIALIZE_REQUEST);const result=await pending;assert.equal(result.preferredModel,true);assert.equal(f.spawned[0],process.execPath);assert.deepEqual(f.spawned[1].slice(1),["app-server","--listen","stdio://","--strict-config"]);assert.equal(f.spawned[2].shell,false);assert.equal(f.spawned[2].env.OPENAI_API_KEY,undefined);assert.deepEqual(f.writes.map(x=>x.method),["initialize","initialized","account/read","account/rateLimits/read","model/list"]);assert.deepEqual(f.writes[1],INITIALIZED_NOTIFICATION);assert.equal(Object.hasOwn(f.writes[1],"jsonrpc"),false);assert.equal(Object.hasOwn(f.writes[1],"id"),false);assert.equal(Object.hasOwn(f.writes[1],"params"),false);assert.deepEqual(f.writes[2],{id:2,method:"account/read",params:{refreshToken:false}});assert.deepEqual(f.writes[3],{id:3,method:"account/rateLimits/read"});assert.deepEqual(f.writes[4],{id:4,method:"model/list",params:{includeHidden:true,limit:100}});for(const write of f.writes)assert.equal(Object.hasOwn(write,"jsonrpc"),false)});
test("unexpected jsonrpc response property is tolerated",async()=>{const f=fake(m=>{const response=success(m) as any;if(response)response.jsonrpc="2.0";return response});assert.equal((await readPrimaryStatus(f.spawn)).preferredModel,true)});
test("account request waits for initialization",async()=>{const f=fake(()=>undefined);const pending=readPrimaryStatus(f.spawn,5);assert.deepEqual(f.writes.map(x=>x.method),["initialize"]);await pending});
for(const [name,response] of [["mismatched id",{id:9,result:{}}],["rpc error",{id:1,error:{code:-1,message:"x"}}],["malformed initialize null",{id:1,result:null}],["malformed initialize empty",{id:1,result:{}}],["malformed initialize missing field",{id:1,result:{userAgent:"x",codexHome:"C:\\x",platformFamily:"windows"}}],["malformed initialize wrong field type",{id:1,result:{userAgent:"x",codexHome:1,platformFamily:"windows",platformOs:"windows"}}],["malformed json","not-json"]] as const)test(name,async()=>{const f=fake(m=>m.method==="initialize"?response:undefined);assert.equal((await readPrimaryStatus(f.spawn)).code,"PRIMARY_STATUS_PROTOCOL_ERROR");assert.deepEqual(f.writes.map(x=>x.method),["initialize"])});
test("response result and error must be exclusive",async()=>{for(const response of [{id:1},{id:1,result:{},error:{code:-1,message:"x"}}]){const f=fake(m=>m.method==="initialize"?response:undefined);assert.equal((await readPrimaryStatus(f.spawn)).code,"PRIMARY_STATUS_PROTOCOL_ERROR")}});
test("headerless malformed method results fail closed",async()=>{for(const stage of ["account","rate","model"]){const f=fake(m=>{if(m.method==="initialize")return{id:1,result:{userAgent:"codex_cli_rs/0.147.0",codexHome:"C:\\Users\\test\\.codex",platformFamily:"windows",platformOs:"windows"}};if(m.method==="account/read")return stage==="account"?{id:2,result:{}}:{id:2,result:account};if(m.method==="account/rateLimits/read")return stage==="rate"?{id:3,result:{}}:{id:3,result:rate};if(m.method==="model/list")return{id:4,result:stage==="model"?{data:[],nextCursor:{}}:{data:[sol],nextCursor:null}}});assert.equal((await readPrimaryStatus(f.spawn)).code,"PRIMARY_STATUS_PROTOCOL_ERROR")}});
test("well-formed notification ignored but unknown response id rejected",async()=>{const f=fake(m=>m.method==="initialize"?[{jsonrpc:"2.0",method:"notice"},{jsonrpc:"2.0",id:8,result:{}}]:undefined);assert.equal((await readPrimaryStatus(f.spawn)).code,"PRIMARY_STATUS_PROTOCOL_ERROR")});
test("malformed account and rate limit fail closed",async()=>{for(const stage of ["account","rate"]){const f=fake(m=>{if(m.method==="initialize")return{jsonrpc:"2.0",id:1,result:{}};if(m.method==="account/read")return{jsonrpc:"2.0",id:2,result:stage==="account"?{}:account};if(m.method==="account/rateLimits/read")return{jsonrpc:"2.0",id:3,result:{}}});assert.equal((await readPrimaryStatus(f.spawn)).code,"PRIMARY_STATUS_PROTOCOL_ERROR")}});
test("pagination follows nextCursor",async()=>{const f=fake(m=>{const base=success(m) as any;if(m.method==="model/list"&&m.id===4)return{jsonrpc:"2.0",id:4,result:{data:[],nextCursor:"next"}};if(m.method==="model/list"&&m.id===5)return{jsonrpc:"2.0",id:5,result:{data:[sol],nextCursor:null}};return base});assert.equal((await readPrimaryStatus(f.spawn)).preferredModel,true);assert.equal(f.writes[5].params.cursor,"next")});
test("repeated cursor and pagination overflow fail",async()=>{const repeated=fake(m=>{const base=success(m) as any;if(m.method==="model/list")return{jsonrpc:"2.0",id:m.id,result:{data:[],nextCursor:"same"}};return base});assert.equal((await readPrimaryStatus(repeated.spawn)).code,"PRIMARY_STATUS_PROTOCOL_ERROR");const overflow=fake(m=>{const base=success(m) as any;if(m.method==="model/list")return{jsonrpc:"2.0",id:m.id,result:{data:[],nextCursor:`c${m.id}`}};return base});assert.equal((await readPrimaryStatus(overflow.spawn)).code,"PRIMARY_STATUS_PROTOCOL_ERROR")});
test("identical duplicate models collapse on same and separate pages",async()=>{const same=fake(m=>{const base=success(m) as any;if(m.method==="model/list")return{jsonrpc:"2.0",id:4,result:{data:[sol,{...sol}],nextCursor:null}};return base});assert.equal((await readPrimaryStatus(same.spawn)).preferredModel,true);const across=fake(m=>{const base=success(m) as any;if(m.method==="model/list"&&m.id===4)return{jsonrpc:"2.0",id:4,result:{data:[sol],nextCursor:"n"}};if(m.method==="model/list")return{jsonrpc:"2.0",id:5,result:{data:[{...sol}],nextCursor:null}};return base});assert.equal((await readPrimaryStatus(across.spawn)).preferredModel,true)});
test("conflicting duplicates fail on same and separate pages",async()=>{for(const across of [false,true]){const f=fake(m=>{const base=success(m) as any;if(m.method==="model/list"&&m.id===4)return{jsonrpc:"2.0",id:4,result:{data:across?[sol]:[sol,{...sol,inputModalities:[]}],nextCursor:across?"n":null}};if(m.method==="model/list")return{jsonrpc:"2.0",id:5,result:{data:[{...sol,inputModalities:[]}],nextCursor:null}};return base});assert.equal((await readPrimaryStatus(f.spawn)).code,"PRIMARY_STATUS_PROTOCOL_ERROR")}});
test("duplicate terminal response id fails closed",async()=>{const f=fake(m=>{const base=success(m) as any;if(m.method==="model/list")return[base,{...base}];return base});assert.equal((await readPrimaryStatus(f.spawn)).code,"PRIMARY_STATUS_PROTOCOL_ERROR")});
test("invalid model records and missing preferred model fail safely",async()=>{for(const bad of [{model:"x",inputModalities:["text"]},{id:"x",inputModalities:["text"]},{id:"x",model:"x",inputModalities:"text"},{id:"x",model:"x",inputModalities:[1]}]){const f=fake(m=>{const base=success(m) as any;if(m.method==="model/list")return{jsonrpc:"2.0",id:4,result:{data:[bad],nextCursor:null}};return base});assert.equal((await readPrimaryStatus(f.spawn)).code,"PRIMARY_STATUS_PROTOCOL_ERROR")}const missing=fake(m=>{const base=success(m) as any;if(m.method==="model/list")return{jsonrpc:"2.0",id:4,result:{data:[{id:"x",model:"x",inputModalities:["text"]}],nextCursor:null}};return base});assert.equal((await readPrimaryStatus(missing.spawn)).preferredModel,false)});
test("preferred model id/model mismatch is protocol invalid",async()=>{for(const bad of [{id:"gpt-5.6-sol",model:"other",inputModalities:["text"]},{id:"other",model:"gpt-5.6-sol",inputModalities:["text"]}]){const f=fake(m=>{const base=success(m) as any;if(m.method==="model/list")return{jsonrpc:"2.0",id:4,result:{data:[bad],nextCursor:null}};return base});assert.equal((await readPrimaryStatus(f.spawn)).code,"PRIMARY_STATUS_PROTOCOL_ERROR")}});
test("timeout and early exit become unknown and shutdown is safe",async()=>{const timeout=fake(()=>undefined);assert.equal((await readPrimaryStatus(timeout.spawn,5)).code,"PRIMARY_STATUS_TIMEOUT");const early=fake(()=>undefined);queueMicrotask(()=>early.child.emit("exit",1));assert.equal((await readPrimaryStatus(early.spawn)).code,"PRIMARY_STATUS_PROTOCOL_ERROR");const clean=fake(success);await readPrimaryStatus(clean.spawn);assert.equal(clean.child.stdin.writableEnded,true)});
