import test from "node:test";import assert from "node:assert/strict";import {parseProviderMode,parseReviewTarget,primaryEnvironment,fallbackEnvironment,openRouterConfig,threadReusable,prepareFallbackExecution} from "../src/core.js";
test("provider modes canonicalize and default",()=>{assert.equal(parseProviderMode(undefined),"auto");assert.equal(parseProviderMode("  PrImArY "),"primary");assert.equal(parseProviderMode(" OPENROUTER-FREE "),"openrouter-free");assert.throws(()=>parseProviderMode("paid"))});
const isolation={localAppData:"C:\\synthetic-local",filesystem:{mkdir(){},lstat(){return{isDirectory:()=>true,isSymbolicLink:()=>false}},exists(){return false}}};
test("environments enforce exact safety",()=>{const primary=primaryEnvironment({PATH:"x",OPENAI_API_KEY:"secret",OPENROUTER_API_KEY:"other",CODEX_API_KEY:"secret",GITHUB_TOKEN:"no",RANDOM_VALUE:"no",CODEX_HOME:"caller"});assert.deepEqual(primary,{PATH:"x"});const f=fallbackEnvironment({Path:"x",LOCALAPPDATA:"C:\\ignored",CODEX_HOME:"caller",OPENROUTER_API_KEY:"free",OPENAI_API_KEY:"paid",CODEX_API_KEY:"secret",GITHUB_TOKEN:"no",RANDOM_KEY:"no"},isolation);assert.equal(f.CODEX_HOME,"C:\\ignored\\print-engineer-codex\\openrouter-home-v1");assert.equal(f.OPENROUTER_API_KEY,"free");assert.equal(f.OPENAI_API_KEY,undefined);assert.equal(f.CODEX_API_KEY,undefined);const config:any=openRouterConfig();assert.equal(config.agents.enabled,false);assert.deepEqual(config,{model_provider:"openrouter",model_providers:{openrouter:{name:"OpenRouter",base_url:"https://openrouter.ai/api/v1",env_key:"OPENROUTER_API_KEY",requires_openai_auth:false,wire_api:"responses",request_max_retries:0,stream_max_retries:0,supports_websockets:false}},agents:{enabled:false}})});
test("fallback home validation is fail closed",()=>{for(const value of [undefined,"","relative"]){assert.throws(()=>prepareFallbackExecution({LOCALAPPDATA:value},isolation),/OPENROUTER_CODEX_HOME_INVALID/)}assert.throws(()=>prepareFallbackExecution({LOCALAPPDATA:"C:\\ok"},{...isolation,filesystem:{...isolation.filesystem,mkdir(){throw new Error("mkdir")}}}),/OPENROUTER_CODEX_HOME_INVALID/);assert.throws(()=>prepareFallbackExecution({LOCALAPPDATA:"C:\\ok"},{...isolation,filesystem:{...isolation.filesystem,lstat(){throw new Error("lstat")}}}),/OPENROUTER_CODEX_HOME_INVALID/);assert.throws(()=>prepareFallbackExecution({LOCALAPPDATA:"C:\\ok"},{...isolation,filesystem:{...isolation.filesystem,exists(){return true}}}),/OPENROUTER_CODEX_HOME_AUTH_PRESENT/)})
test("identity gates resume",()=>{const s={schemaVersion:2,providerMode:"primary",modelIdentity:"gpt-5.6-sol",role:"build",worktree:"w"};assert.equal(threadReusable(s,"primary","gpt-5.6-sol","build","w"),true);assert.equal(threadReusable(s,"openrouter-free","x","build","w"),false)});
test("provider and model changes force fresh while same durable worktree may resume",()=>{const state={schemaVersion:2,providerMode:"openrouter-free",modelIdentity:"v/a:free",role:"build",worktree:"same"};assert.equal(threadReusable(state,"openrouter-free","v/a:free","build","same"),true);assert.equal(threadReusable(state,"primary","gpt-5.6-sol","build","same"),false);assert.equal(threadReusable(state,"openrouter-free","v/b:free","build","same"),false);assert.equal(threadReusable(state,"openrouter-free","v/a:free","build","other"),false)});
test("review target is exact",()=>{assert.equal(parseReviewTarget(" PLAN "),"plan");assert.equal(parseReviewTarget("implementation"),"implementation");assert.throws(()=>parseReviewTarget("code"))});
test("fallback lstat rejects files and links",()=>{for(const bad of [{isDirectory:()=>false,isSymbolicLink:()=>false},{isDirectory:()=>true,isSymbolicLink:()=>true}])assert.throws(()=>prepareFallbackExecution({}, {...isolation,filesystem:{...isolation.filesystem,lstat:()=>bad}}),/OPENROUTER_CODEX_HOME_INVALID/)})
test("fallback creates missing parent and home and preserves existing directories",()=>{const created=new Set<string>();let mkdirCalls=0;const fs:any={mkdir(path:string){mkdirCalls++;created.add(path)},lstat(path:string){return{isDirectory:()=>created.has(path),isSymbolicLink:()=>false}},exists(){return false}};const first=prepareFallbackExecution({LOCALAPPDATA:"C:\\local",OPENROUTER_API_KEY:"key"},{filesystem:fs});assert.equal(created.size,2);assert.equal(mkdirCalls,2);assert.equal(first.environment.CODEX_HOME,"C:\\local\\print-engineer-codex\\openrouter-home-v1");const second=prepareFallbackExecution({LOCALAPPDATA:"C:\\local",OPENROUTER_API_KEY:"key"},{filesystem:fs});assert.equal(second.home,first.home);assert.equal(mkdirCalls,4);assert.equal(created.size,2)})
test("fallback accepts existing parent and creates only missing home",()=>{const parent="C:\\local\\print-engineer-codex",home=`${parent}\\openrouter-home-v1`;const existing=new Set([parent]);let parentLstatCount=0;const mkdirPaths:string[]=[];const fs:any={mkdir(path:string){mkdirPaths.push(path);if(path===home)existing.add(path);else assert.equal(path,parent)},lstat(path:string){assert.ok(existing.has(path));if(path===parent)parentLstatCount++;return{isDirectory:()=>true,isSymbolicLink:()=>false}},exists(){return false}};const prepared=prepareFallbackExecution({LOCALAPPDATA:"C:\\local",OPENROUTER_API_KEY:"key"},{filesystem:fs});assert.deepEqual(mkdirPaths,[parent,home]);assert.ok(parentLstatCount>0);assert.ok(existing.has(parent));assert.ok(existing.has(home));assert.equal(prepared.home,home);assert.equal(prepared.environment.CODEX_HOME,home)})
test("fallback distinguishes parent and home regular files",()=>{for(const badPath of ["parent","home"]){const parent="C:\\local\\print-engineer-codex",home=`${parent}\\openrouter-home-v1`;const fs:any={mkdir(){},lstat(path:string){return{isDirectory:()=>path!==(badPath==="parent"?parent:home),isSymbolicLink:()=>false}},exists(){return false}};assert.throws(()=>prepareFallbackExecution({LOCALAPPDATA:"C:\\local"},{filesystem:fs}),/OPENROUTER_CODEX_HOME_INVALID/);}})
test("fallback rejects parent and home symbolic links independently",()=>{for(const badPath of ["parent","home"]){const parent="C:\\local\\print-engineer-codex",home=`${parent}\\openrouter-home-v1`;const fs:any={mkdir(){},lstat(path:string){return{isDirectory:()=>true,isSymbolicLink:()=>path===(badPath==="parent"?parent:home)}},exists(){return false}};assert.throws(()=>prepareFallbackExecution({LOCALAPPDATA:"C:\\local"},{filesystem:fs}),/OPENROUTER_CODEX_HOME_INVALID/);}})
test("fallback fails closed for mkdir, parent lstat, home lstat, and missing classification",()=>{const parent="C:\\local\\print-engineer-codex",home=`${parent}\\openrouter-home-v1`;for(const failure of ["mkdir","parent-lstat","home-lstat","missing"]){let calls=0;const fs:any={mkdir(path:string){calls++;if(failure==="mkdir")throw new Error("secret")},lstat(path:string){if(failure==="parent-lstat"&&path===parent)throw new Error("secret");if(failure==="home-lstat"&&path===home)throw new Error("secret");return{isDirectory:()=>failure!=="missing",isSymbolicLink:()=>false}},exists(){return false}};assert.throws(()=>prepareFallbackExecution({LOCALAPPDATA:"C:\\local"},{filesystem:fs}),/OPENROUTER_CODEX_HOME_INVALID/);assert.ok(calls>=1);}})
test("auth existence is checked without reading or deleting contents",()=>{let reads=0,deletes=0;const fs:any={mkdir(){},lstat(){return{isDirectory:()=>true,isSymbolicLink:()=>false}},exists(path:string){assert.match(path,/auth\.json$/);return true},readFile(){reads++;throw new Error("AUTH_CONTENT_MUST_NOT_BE_READ")},readFileSync(){reads++;throw new Error("AUTH_CONTENT_MUST_NOT_BE_READ")},unlink(){deletes++},unlinkSync(){deletes++},rename(){deletes++},renameSync(){deletes++}};assert.throws(()=>prepareFallbackExecution({LOCALAPPDATA:"C:\\local"},{filesystem:fs}),/OPENROUTER_CODEX_HOME_AUTH_PRESENT/);assert.equal(reads,0);assert.equal(deletes,0)})
